package com.megaeyes.persistence.ibatis.model;

public class AcAccessServers {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.NAME
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.NAMING
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String naming;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.ACCESS_PASSWORD
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String accessPassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.INSTALL_LOCATION
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String installLocation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.DEVICE_NUMBER
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String deviceNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.IP
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String ip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.NOTE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String note;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.MESSAGE_PORT
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private Integer messagePort;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.DEVICE_TYPE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String deviceType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.STATUS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.ORGAN_ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String organId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.GATEWAY_ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private String gatewayId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.SUBADDR
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private Integer subaddr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.AC_ACCESS_SERVERS.MODEL_TYPE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private Short modelType;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.ID
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.ID
     *
     * @param id the value for HBDW1.AC_ACCESS_SERVERS.ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.NAME
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.NAME
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.NAME
     *
     * @param name the value for HBDW1.AC_ACCESS_SERVERS.NAME
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.NAMING
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.NAMING
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getNaming() {
        return naming;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.NAMING
     *
     * @param naming the value for HBDW1.AC_ACCESS_SERVERS.NAMING
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setNaming(String naming) {
        this.naming = naming;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.ACCESS_PASSWORD
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.ACCESS_PASSWORD
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getAccessPassword() {
        return accessPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.ACCESS_PASSWORD
     *
     * @param accessPassword the value for HBDW1.AC_ACCESS_SERVERS.ACCESS_PASSWORD
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setAccessPassword(String accessPassword) {
        this.accessPassword = accessPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.INSTALL_LOCATION
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.INSTALL_LOCATION
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getInstallLocation() {
        return installLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.INSTALL_LOCATION
     *
     * @param installLocation the value for HBDW1.AC_ACCESS_SERVERS.INSTALL_LOCATION
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setInstallLocation(String installLocation) {
        this.installLocation = installLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.DEVICE_NUMBER
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.DEVICE_NUMBER
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.DEVICE_NUMBER
     *
     * @param deviceNumber the value for HBDW1.AC_ACCESS_SERVERS.DEVICE_NUMBER
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.IP
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.IP
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.IP
     *
     * @param ip the value for HBDW1.AC_ACCESS_SERVERS.IP
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.NOTE
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.NOTE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.NOTE
     *
     * @param note the value for HBDW1.AC_ACCESS_SERVERS.NOTE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.MESSAGE_PORT
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.MESSAGE_PORT
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public Integer getMessagePort() {
        return messagePort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.MESSAGE_PORT
     *
     * @param messagePort the value for HBDW1.AC_ACCESS_SERVERS.MESSAGE_PORT
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setMessagePort(Integer messagePort) {
        this.messagePort = messagePort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.DEVICE_TYPE
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.DEVICE_TYPE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.DEVICE_TYPE
     *
     * @param deviceType the value for HBDW1.AC_ACCESS_SERVERS.DEVICE_TYPE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.STATUS
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.STATUS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.STATUS
     *
     * @param status the value for HBDW1.AC_ACCESS_SERVERS.STATUS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.ORGAN_ID
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.ORGAN_ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.ORGAN_ID
     *
     * @param organId the value for HBDW1.AC_ACCESS_SERVERS.ORGAN_ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.GATEWAY_ID
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.GATEWAY_ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.GATEWAY_ID
     *
     * @param gatewayId the value for HBDW1.AC_ACCESS_SERVERS.GATEWAY_ID
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setGatewayId(String gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.SUBADDR
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.SUBADDR
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public Integer getSubaddr() {
        return subaddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.SUBADDR
     *
     * @param subaddr the value for HBDW1.AC_ACCESS_SERVERS.SUBADDR
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setSubaddr(Integer subaddr) {
        this.subaddr = subaddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.AC_ACCESS_SERVERS.MODEL_TYPE
     *
     * @return the value of HBDW1.AC_ACCESS_SERVERS.MODEL_TYPE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public Short getModelType() {
        return modelType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.AC_ACCESS_SERVERS.MODEL_TYPE
     *
     * @param modelType the value for HBDW1.AC_ACCESS_SERVERS.MODEL_TYPE
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setModelType(Short modelType) {
        this.modelType = modelType;
    }
}