package com.megaeyes.persistence.ibatis.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AcAccessServersExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public AcAccessServersExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    protected AcAccessServersExample(AcAccessServersExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andNamingIsNull() {
            addCriterion("NAMING is null");
            return this;
        }

        public Criteria andNamingIsNotNull() {
            addCriterion("NAMING is not null");
            return this;
        }

        public Criteria andNamingEqualTo(String value) {
            addCriterion("NAMING =", value, "naming");
            return this;
        }

        public Criteria andNamingNotEqualTo(String value) {
            addCriterion("NAMING <>", value, "naming");
            return this;
        }

        public Criteria andNamingGreaterThan(String value) {
            addCriterion("NAMING >", value, "naming");
            return this;
        }

        public Criteria andNamingGreaterThanOrEqualTo(String value) {
            addCriterion("NAMING >=", value, "naming");
            return this;
        }

        public Criteria andNamingLessThan(String value) {
            addCriterion("NAMING <", value, "naming");
            return this;
        }

        public Criteria andNamingLessThanOrEqualTo(String value) {
            addCriterion("NAMING <=", value, "naming");
            return this;
        }

        public Criteria andNamingLike(String value) {
            addCriterion("NAMING like", value, "naming");
            return this;
        }

        public Criteria andNamingNotLike(String value) {
            addCriterion("NAMING not like", value, "naming");
            return this;
        }

        public Criteria andNamingIn(List values) {
            addCriterion("NAMING in", values, "naming");
            return this;
        }

        public Criteria andNamingNotIn(List values) {
            addCriterion("NAMING not in", values, "naming");
            return this;
        }

        public Criteria andNamingBetween(String value1, String value2) {
            addCriterion("NAMING between", value1, value2, "naming");
            return this;
        }

        public Criteria andNamingNotBetween(String value1, String value2) {
            addCriterion("NAMING not between", value1, value2, "naming");
            return this;
        }

        public Criteria andAccessPasswordIsNull() {
            addCriterion("ACCESS_PASSWORD is null");
            return this;
        }

        public Criteria andAccessPasswordIsNotNull() {
            addCriterion("ACCESS_PASSWORD is not null");
            return this;
        }

        public Criteria andAccessPasswordEqualTo(String value) {
            addCriterion("ACCESS_PASSWORD =", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordNotEqualTo(String value) {
            addCriterion("ACCESS_PASSWORD <>", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordGreaterThan(String value) {
            addCriterion("ACCESS_PASSWORD >", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("ACCESS_PASSWORD >=", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordLessThan(String value) {
            addCriterion("ACCESS_PASSWORD <", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordLessThanOrEqualTo(String value) {
            addCriterion("ACCESS_PASSWORD <=", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordLike(String value) {
            addCriterion("ACCESS_PASSWORD like", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordNotLike(String value) {
            addCriterion("ACCESS_PASSWORD not like", value, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordIn(List values) {
            addCriterion("ACCESS_PASSWORD in", values, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordNotIn(List values) {
            addCriterion("ACCESS_PASSWORD not in", values, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordBetween(String value1, String value2) {
            addCriterion("ACCESS_PASSWORD between", value1, value2, "accessPassword");
            return this;
        }

        public Criteria andAccessPasswordNotBetween(String value1, String value2) {
            addCriterion("ACCESS_PASSWORD not between", value1, value2, "accessPassword");
            return this;
        }

        public Criteria andInstallLocationIsNull() {
            addCriterion("INSTALL_LOCATION is null");
            return this;
        }

        public Criteria andInstallLocationIsNotNull() {
            addCriterion("INSTALL_LOCATION is not null");
            return this;
        }

        public Criteria andInstallLocationEqualTo(String value) {
            addCriterion("INSTALL_LOCATION =", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationNotEqualTo(String value) {
            addCriterion("INSTALL_LOCATION <>", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationGreaterThan(String value) {
            addCriterion("INSTALL_LOCATION >", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationGreaterThanOrEqualTo(String value) {
            addCriterion("INSTALL_LOCATION >=", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationLessThan(String value) {
            addCriterion("INSTALL_LOCATION <", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationLessThanOrEqualTo(String value) {
            addCriterion("INSTALL_LOCATION <=", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationLike(String value) {
            addCriterion("INSTALL_LOCATION like", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationNotLike(String value) {
            addCriterion("INSTALL_LOCATION not like", value, "installLocation");
            return this;
        }

        public Criteria andInstallLocationIn(List values) {
            addCriterion("INSTALL_LOCATION in", values, "installLocation");
            return this;
        }

        public Criteria andInstallLocationNotIn(List values) {
            addCriterion("INSTALL_LOCATION not in", values, "installLocation");
            return this;
        }

        public Criteria andInstallLocationBetween(String value1, String value2) {
            addCriterion("INSTALL_LOCATION between", value1, value2, "installLocation");
            return this;
        }

        public Criteria andInstallLocationNotBetween(String value1, String value2) {
            addCriterion("INSTALL_LOCATION not between", value1, value2, "installLocation");
            return this;
        }

        public Criteria andDeviceNumberIsNull() {
            addCriterion("DEVICE_NUMBER is null");
            return this;
        }

        public Criteria andDeviceNumberIsNotNull() {
            addCriterion("DEVICE_NUMBER is not null");
            return this;
        }

        public Criteria andDeviceNumberEqualTo(String value) {
            addCriterion("DEVICE_NUMBER =", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberNotEqualTo(String value) {
            addCriterion("DEVICE_NUMBER <>", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberGreaterThan(String value) {
            addCriterion("DEVICE_NUMBER >", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberGreaterThanOrEqualTo(String value) {
            addCriterion("DEVICE_NUMBER >=", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberLessThan(String value) {
            addCriterion("DEVICE_NUMBER <", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberLessThanOrEqualTo(String value) {
            addCriterion("DEVICE_NUMBER <=", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberLike(String value) {
            addCriterion("DEVICE_NUMBER like", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberNotLike(String value) {
            addCriterion("DEVICE_NUMBER not like", value, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberIn(List values) {
            addCriterion("DEVICE_NUMBER in", values, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberNotIn(List values) {
            addCriterion("DEVICE_NUMBER not in", values, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberBetween(String value1, String value2) {
            addCriterion("DEVICE_NUMBER between", value1, value2, "deviceNumber");
            return this;
        }

        public Criteria andDeviceNumberNotBetween(String value1, String value2) {
            addCriterion("DEVICE_NUMBER not between", value1, value2, "deviceNumber");
            return this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return this;
        }

        public Criteria andIpIn(List values) {
            addCriterion("IP in", values, "ip");
            return this;
        }

        public Criteria andIpNotIn(List values) {
            addCriterion("IP not in", values, "ip");
            return this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return this;
        }

        public Criteria andNoteIn(List values) {
            addCriterion("NOTE in", values, "note");
            return this;
        }

        public Criteria andNoteNotIn(List values) {
            addCriterion("NOTE not in", values, "note");
            return this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return this;
        }

        public Criteria andMessagePortIsNull() {
            addCriterion("MESSAGE_PORT is null");
            return this;
        }

        public Criteria andMessagePortIsNotNull() {
            addCriterion("MESSAGE_PORT is not null");
            return this;
        }

        public Criteria andMessagePortEqualTo(Integer value) {
            addCriterion("MESSAGE_PORT =", value, "messagePort");
            return this;
        }

        public Criteria andMessagePortNotEqualTo(Integer value) {
            addCriterion("MESSAGE_PORT <>", value, "messagePort");
            return this;
        }

        public Criteria andMessagePortGreaterThan(Integer value) {
            addCriterion("MESSAGE_PORT >", value, "messagePort");
            return this;
        }

        public Criteria andMessagePortGreaterThanOrEqualTo(Integer value) {
            addCriterion("MESSAGE_PORT >=", value, "messagePort");
            return this;
        }

        public Criteria andMessagePortLessThan(Integer value) {
            addCriterion("MESSAGE_PORT <", value, "messagePort");
            return this;
        }

        public Criteria andMessagePortLessThanOrEqualTo(Integer value) {
            addCriterion("MESSAGE_PORT <=", value, "messagePort");
            return this;
        }

        public Criteria andMessagePortIn(List values) {
            addCriterion("MESSAGE_PORT in", values, "messagePort");
            return this;
        }

        public Criteria andMessagePortNotIn(List values) {
            addCriterion("MESSAGE_PORT not in", values, "messagePort");
            return this;
        }

        public Criteria andMessagePortBetween(Integer value1, Integer value2) {
            addCriterion("MESSAGE_PORT between", value1, value2, "messagePort");
            return this;
        }

        public Criteria andMessagePortNotBetween(Integer value1, Integer value2) {
            addCriterion("MESSAGE_PORT not between", value1, value2, "messagePort");
            return this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("DEVICE_TYPE is null");
            return this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("DEVICE_TYPE is not null");
            return this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("DEVICE_TYPE =", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("DEVICE_TYPE <>", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("DEVICE_TYPE >", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DEVICE_TYPE >=", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("DEVICE_TYPE <", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("DEVICE_TYPE <=", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("DEVICE_TYPE like", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("DEVICE_TYPE not like", value, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeIn(List values) {
            addCriterion("DEVICE_TYPE in", values, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeNotIn(List values) {
            addCriterion("DEVICE_TYPE not in", values, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("DEVICE_TYPE between", value1, value2, "deviceType");
            return this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("DEVICE_TYPE not between", value1, value2, "deviceType");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andOrganIdIsNull() {
            addCriterion("ORGAN_ID is null");
            return this;
        }

        public Criteria andOrganIdIsNotNull() {
            addCriterion("ORGAN_ID is not null");
            return this;
        }

        public Criteria andOrganIdEqualTo(String value) {
            addCriterion("ORGAN_ID =", value, "organId");
            return this;
        }

        public Criteria andOrganIdNotEqualTo(String value) {
            addCriterion("ORGAN_ID <>", value, "organId");
            return this;
        }

        public Criteria andOrganIdGreaterThan(String value) {
            addCriterion("ORGAN_ID >", value, "organId");
            return this;
        }

        public Criteria andOrganIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORGAN_ID >=", value, "organId");
            return this;
        }

        public Criteria andOrganIdLessThan(String value) {
            addCriterion("ORGAN_ID <", value, "organId");
            return this;
        }

        public Criteria andOrganIdLessThanOrEqualTo(String value) {
            addCriterion("ORGAN_ID <=", value, "organId");
            return this;
        }

        public Criteria andOrganIdLike(String value) {
            addCriterion("ORGAN_ID like", value, "organId");
            return this;
        }

        public Criteria andOrganIdNotLike(String value) {
            addCriterion("ORGAN_ID not like", value, "organId");
            return this;
        }

        public Criteria andOrganIdIn(List values) {
            addCriterion("ORGAN_ID in", values, "organId");
            return this;
        }

        public Criteria andOrganIdNotIn(List values) {
            addCriterion("ORGAN_ID not in", values, "organId");
            return this;
        }

        public Criteria andOrganIdBetween(String value1, String value2) {
            addCriterion("ORGAN_ID between", value1, value2, "organId");
            return this;
        }

        public Criteria andOrganIdNotBetween(String value1, String value2) {
            addCriterion("ORGAN_ID not between", value1, value2, "organId");
            return this;
        }

        public Criteria andGatewayIdIsNull() {
            addCriterion("GATEWAY_ID is null");
            return this;
        }

        public Criteria andGatewayIdIsNotNull() {
            addCriterion("GATEWAY_ID is not null");
            return this;
        }

        public Criteria andGatewayIdEqualTo(String value) {
            addCriterion("GATEWAY_ID =", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdNotEqualTo(String value) {
            addCriterion("GATEWAY_ID <>", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdGreaterThan(String value) {
            addCriterion("GATEWAY_ID >", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdGreaterThanOrEqualTo(String value) {
            addCriterion("GATEWAY_ID >=", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdLessThan(String value) {
            addCriterion("GATEWAY_ID <", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdLessThanOrEqualTo(String value) {
            addCriterion("GATEWAY_ID <=", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdLike(String value) {
            addCriterion("GATEWAY_ID like", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdNotLike(String value) {
            addCriterion("GATEWAY_ID not like", value, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdIn(List values) {
            addCriterion("GATEWAY_ID in", values, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdNotIn(List values) {
            addCriterion("GATEWAY_ID not in", values, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdBetween(String value1, String value2) {
            addCriterion("GATEWAY_ID between", value1, value2, "gatewayId");
            return this;
        }

        public Criteria andGatewayIdNotBetween(String value1, String value2) {
            addCriterion("GATEWAY_ID not between", value1, value2, "gatewayId");
            return this;
        }

        public Criteria andSubaddrIsNull() {
            addCriterion("SUBADDR is null");
            return this;
        }

        public Criteria andSubaddrIsNotNull() {
            addCriterion("SUBADDR is not null");
            return this;
        }

        public Criteria andSubaddrEqualTo(Integer value) {
            addCriterion("SUBADDR =", value, "subaddr");
            return this;
        }

        public Criteria andSubaddrNotEqualTo(Integer value) {
            addCriterion("SUBADDR <>", value, "subaddr");
            return this;
        }

        public Criteria andSubaddrGreaterThan(Integer value) {
            addCriterion("SUBADDR >", value, "subaddr");
            return this;
        }

        public Criteria andSubaddrGreaterThanOrEqualTo(Integer value) {
            addCriterion("SUBADDR >=", value, "subaddr");
            return this;
        }

        public Criteria andSubaddrLessThan(Integer value) {
            addCriterion("SUBADDR <", value, "subaddr");
            return this;
        }

        public Criteria andSubaddrLessThanOrEqualTo(Integer value) {
            addCriterion("SUBADDR <=", value, "subaddr");
            return this;
        }

        public Criteria andSubaddrIn(List values) {
            addCriterion("SUBADDR in", values, "subaddr");
            return this;
        }

        public Criteria andSubaddrNotIn(List values) {
            addCriterion("SUBADDR not in", values, "subaddr");
            return this;
        }

        public Criteria andSubaddrBetween(Integer value1, Integer value2) {
            addCriterion("SUBADDR between", value1, value2, "subaddr");
            return this;
        }

        public Criteria andSubaddrNotBetween(Integer value1, Integer value2) {
            addCriterion("SUBADDR not between", value1, value2, "subaddr");
            return this;
        }

        public Criteria andModelTypeIsNull() {
            addCriterion("MODEL_TYPE is null");
            return this;
        }

        public Criteria andModelTypeIsNotNull() {
            addCriterion("MODEL_TYPE is not null");
            return this;
        }

        public Criteria andModelTypeEqualTo(Short value) {
            addCriterion("MODEL_TYPE =", value, "modelType");
            return this;
        }

        public Criteria andModelTypeNotEqualTo(Short value) {
            addCriterion("MODEL_TYPE <>", value, "modelType");
            return this;
        }

        public Criteria andModelTypeGreaterThan(Short value) {
            addCriterion("MODEL_TYPE >", value, "modelType");
            return this;
        }

        public Criteria andModelTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("MODEL_TYPE >=", value, "modelType");
            return this;
        }

        public Criteria andModelTypeLessThan(Short value) {
            addCriterion("MODEL_TYPE <", value, "modelType");
            return this;
        }

        public Criteria andModelTypeLessThanOrEqualTo(Short value) {
            addCriterion("MODEL_TYPE <=", value, "modelType");
            return this;
        }

        public Criteria andModelTypeIn(List values) {
            addCriterion("MODEL_TYPE in", values, "modelType");
            return this;
        }

        public Criteria andModelTypeNotIn(List values) {
            addCriterion("MODEL_TYPE not in", values, "modelType");
            return this;
        }

        public Criteria andModelTypeBetween(Short value1, Short value2) {
            addCriterion("MODEL_TYPE between", value1, value2, "modelType");
            return this;
        }

        public Criteria andModelTypeNotBetween(Short value1, Short value2) {
            addCriterion("MODEL_TYPE not between", value1, value2, "modelType");
            return this;
        }
    }
}