package com.megaeyes.persistence.ibatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class AcAttendanceCheckRecord {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.EMPLOYEE_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String employeeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.ORGAN_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String organId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.BRANCH_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.RECORD_DATETIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private Date recordDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal state;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.LATE_STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal lateState;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.LATE_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal lateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal leaveEarlyState;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal leaveEarlyTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIMES
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal absentTimes;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal absentTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.AFFAIR
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal affair;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.SICK
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal sick;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.START_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String startTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.COME_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private Date comeTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.END_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.GO_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private Date goTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.PRT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private Date prtTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.NEXT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private Date nextTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.FLAG
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private BigDecimal flag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_ATTENDANCE_CHECK_RECORD.REMARK
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private String remark;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.ID
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.ID
     *
     * @param id the value for AC_ATTENDANCE_CHECK_RECORD.ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.EMPLOYEE_ID
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.EMPLOYEE_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.EMPLOYEE_ID
     *
     * @param employeeId the value for AC_ATTENDANCE_CHECK_RECORD.EMPLOYEE_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.ORGAN_ID
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.ORGAN_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.ORGAN_ID
     *
     * @param organId the value for AC_ATTENDANCE_CHECK_RECORD.ORGAN_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.BRANCH_ID
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.BRANCH_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.BRANCH_ID
     *
     * @param branchId the value for AC_ATTENDANCE_CHECK_RECORD.BRANCH_ID
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.RECORD_DATETIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.RECORD_DATETIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public Date getRecordDatetime() {
        return recordDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.RECORD_DATETIME
     *
     * @param recordDatetime the value for AC_ATTENDANCE_CHECK_RECORD.RECORD_DATETIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setRecordDatetime(Date recordDatetime) {
        this.recordDatetime = recordDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.STATE
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.STATE
     *
     * @param state the value for AC_ATTENDANCE_CHECK_RECORD.STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.LATE_STATE
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.LATE_STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getLateState() {
        return lateState;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.LATE_STATE
     *
     * @param lateState the value for AC_ATTENDANCE_CHECK_RECORD.LATE_STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setLateState(BigDecimal lateState) {
        this.lateState = lateState;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.LATE_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.LATE_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getLateTime() {
        return lateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.LATE_TIME
     *
     * @param lateTime the value for AC_ATTENDANCE_CHECK_RECORD.LATE_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setLateTime(BigDecimal lateTime) {
        this.lateTime = lateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_STATE
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getLeaveEarlyState() {
        return leaveEarlyState;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_STATE
     *
     * @param leaveEarlyState the value for AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_STATE
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setLeaveEarlyState(BigDecimal leaveEarlyState) {
        this.leaveEarlyState = leaveEarlyState;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getLeaveEarlyTime() {
        return leaveEarlyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_TIME
     *
     * @param leaveEarlyTime the value for AC_ATTENDANCE_CHECK_RECORD.LEAVE_EARLY_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setLeaveEarlyTime(BigDecimal leaveEarlyTime) {
        this.leaveEarlyTime = leaveEarlyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIMES
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIMES
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getAbsentTimes() {
        return absentTimes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIMES
     *
     * @param absentTimes the value for AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIMES
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setAbsentTimes(BigDecimal absentTimes) {
        this.absentTimes = absentTimes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getAbsentTime() {
        return absentTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIME
     *
     * @param absentTime the value for AC_ATTENDANCE_CHECK_RECORD.ABSENT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setAbsentTime(BigDecimal absentTime) {
        this.absentTime = absentTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.AFFAIR
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.AFFAIR
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getAffair() {
        return affair;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.AFFAIR
     *
     * @param affair the value for AC_ATTENDANCE_CHECK_RECORD.AFFAIR
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setAffair(BigDecimal affair) {
        this.affair = affair;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.SICK
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.SICK
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getSick() {
        return sick;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.SICK
     *
     * @param sick the value for AC_ATTENDANCE_CHECK_RECORD.SICK
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setSick(BigDecimal sick) {
        this.sick = sick;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.START_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.START_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.START_TIME
     *
     * @param startTime the value for AC_ATTENDANCE_CHECK_RECORD.START_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.COME_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.COME_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public Date getComeTime() {
        return comeTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.COME_TIME
     *
     * @param comeTime the value for AC_ATTENDANCE_CHECK_RECORD.COME_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setComeTime(Date comeTime) {
        this.comeTime = comeTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.END_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.END_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.END_TIME
     *
     * @param endTime the value for AC_ATTENDANCE_CHECK_RECORD.END_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.GO_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.GO_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public Date getGoTime() {
        return goTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.GO_TIME
     *
     * @param goTime the value for AC_ATTENDANCE_CHECK_RECORD.GO_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setGoTime(Date goTime) {
        this.goTime = goTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.PRT_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.PRT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public Date getPrtTime() {
        return prtTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.PRT_TIME
     *
     * @param prtTime the value for AC_ATTENDANCE_CHECK_RECORD.PRT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setPrtTime(Date prtTime) {
        this.prtTime = prtTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.NEXT_TIME
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.NEXT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.NEXT_TIME
     *
     * @param nextTime the value for AC_ATTENDANCE_CHECK_RECORD.NEXT_TIME
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.FLAG
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.FLAG
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public BigDecimal getFlag() {
        return flag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.FLAG
     *
     * @param flag the value for AC_ATTENDANCE_CHECK_RECORD.FLAG
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_ATTENDANCE_CHECK_RECORD.REMARK
     *
     * @return the value of AC_ATTENDANCE_CHECK_RECORD.REMARK
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_ATTENDANCE_CHECK_RECORD.REMARK
     *
     * @param remark the value for AC_ATTENDANCE_CHECK_RECORD.REMARK
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}