package com.megaeyes.persistence.ibatis.model;

import java.util.Date;

public class AcEmployeeGroup {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DL25.AC_EMPLOYEE_GROUP.ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DL25.AC_EMPLOYEE_GROUP.NAME
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DL25.AC_EMPLOYEE_GROUP.ORGAN_ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    private String organId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DL25.AC_EMPLOYEE_GROUP.CREATOR_ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    private String creatorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DL25.AC_EMPLOYEE_GROUP.CREATE_TIME
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DL25.AC_EMPLOYEE_GROUP.NOTE
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    private String note;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DL25.AC_EMPLOYEE_GROUP.ID
     *
     * @return the value of DL25.AC_EMPLOYEE_GROUP.ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DL25.AC_EMPLOYEE_GROUP.ID
     *
     * @param id the value for DL25.AC_EMPLOYEE_GROUP.ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DL25.AC_EMPLOYEE_GROUP.NAME
     *
     * @return the value of DL25.AC_EMPLOYEE_GROUP.NAME
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DL25.AC_EMPLOYEE_GROUP.NAME
     *
     * @param name the value for DL25.AC_EMPLOYEE_GROUP.NAME
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DL25.AC_EMPLOYEE_GROUP.ORGAN_ID
     *
     * @return the value of DL25.AC_EMPLOYEE_GROUP.ORGAN_ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DL25.AC_EMPLOYEE_GROUP.ORGAN_ID
     *
     * @param organId the value for DL25.AC_EMPLOYEE_GROUP.ORGAN_ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DL25.AC_EMPLOYEE_GROUP.CREATOR_ID
     *
     * @return the value of DL25.AC_EMPLOYEE_GROUP.CREATOR_ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DL25.AC_EMPLOYEE_GROUP.CREATOR_ID
     *
     * @param creatorId the value for DL25.AC_EMPLOYEE_GROUP.CREATOR_ID
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DL25.AC_EMPLOYEE_GROUP.CREATE_TIME
     *
     * @return the value of DL25.AC_EMPLOYEE_GROUP.CREATE_TIME
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DL25.AC_EMPLOYEE_GROUP.CREATE_TIME
     *
     * @param createTime the value for DL25.AC_EMPLOYEE_GROUP.CREATE_TIME
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DL25.AC_EMPLOYEE_GROUP.NOTE
     *
     * @return the value of DL25.AC_EMPLOYEE_GROUP.NOTE
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DL25.AC_EMPLOYEE_GROUP.NOTE
     *
     * @param note the value for DL25.AC_EMPLOYEE_GROUP.NOTE
     *
     * @abatorgenerated Fri Jan 11 06:44:15 GMT 2013
     */
    public void setNote(String note) {
        this.note = note;
    }
}