package com.megaeyes.persistence.ibatis.model;

public class AcREmployeeGroup {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_R_EMPLOYEE_GROUP.ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_R_EMPLOYEE_GROUP.GROUP_ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    private String groupId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column AC_R_EMPLOYEE_GROUP.EMPLOYEE_ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    private String employeeId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_R_EMPLOYEE_GROUP.ID
     *
     * @return the value of AC_R_EMPLOYEE_GROUP.ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_R_EMPLOYEE_GROUP.ID
     *
     * @param id the value for AC_R_EMPLOYEE_GROUP.ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_R_EMPLOYEE_GROUP.GROUP_ID
     *
     * @return the value of AC_R_EMPLOYEE_GROUP.GROUP_ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_R_EMPLOYEE_GROUP.GROUP_ID
     *
     * @param groupId the value for AC_R_EMPLOYEE_GROUP.GROUP_ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column AC_R_EMPLOYEE_GROUP.EMPLOYEE_ID
     *
     * @return the value of AC_R_EMPLOYEE_GROUP.EMPLOYEE_ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column AC_R_EMPLOYEE_GROUP.EMPLOYEE_ID
     *
     * @param employeeId the value for AC_R_EMPLOYEE_GROUP.EMPLOYEE_ID
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
}