package com.megaeyes.persistence.ibatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class AcWorkAttendanceRuleExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public AcWorkAttendanceRuleExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    protected AcWorkAttendanceRuleExample(AcWorkAttendanceRuleExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andOrganIdIsNull() {
            addCriterion("ORGAN_ID is null");
            return this;
        }

        public Criteria andOrganIdIsNotNull() {
            addCriterion("ORGAN_ID is not null");
            return this;
        }

        public Criteria andOrganIdEqualTo(String value) {
            addCriterion("ORGAN_ID =", value, "organId");
            return this;
        }

        public Criteria andOrganIdNotEqualTo(String value) {
            addCriterion("ORGAN_ID <>", value, "organId");
            return this;
        }

        public Criteria andOrganIdGreaterThan(String value) {
            addCriterion("ORGAN_ID >", value, "organId");
            return this;
        }

        public Criteria andOrganIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORGAN_ID >=", value, "organId");
            return this;
        }

        public Criteria andOrganIdLessThan(String value) {
            addCriterion("ORGAN_ID <", value, "organId");
            return this;
        }

        public Criteria andOrganIdLessThanOrEqualTo(String value) {
            addCriterion("ORGAN_ID <=", value, "organId");
            return this;
        }

        public Criteria andOrganIdLike(String value) {
            addCriterion("ORGAN_ID like", value, "organId");
            return this;
        }

        public Criteria andOrganIdNotLike(String value) {
            addCriterion("ORGAN_ID not like", value, "organId");
            return this;
        }

        public Criteria andOrganIdIn(List values) {
            addCriterion("ORGAN_ID in", values, "organId");
            return this;
        }

        public Criteria andOrganIdNotIn(List values) {
            addCriterion("ORGAN_ID not in", values, "organId");
            return this;
        }

        public Criteria andOrganIdBetween(String value1, String value2) {
            addCriterion("ORGAN_ID between", value1, value2, "organId");
            return this;
        }

        public Criteria andOrganIdNotBetween(String value1, String value2) {
            addCriterion("ORGAN_ID not between", value1, value2, "organId");
            return this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("CREATOR_ID is null");
            return this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("CREATOR_ID is not null");
            return this;
        }

        public Criteria andCreatorIdEqualTo(String value) {
            addCriterion("CREATOR_ID =", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdNotEqualTo(String value) {
            addCriterion("CREATOR_ID <>", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdGreaterThan(String value) {
            addCriterion("CREATOR_ID >", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR_ID >=", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdLessThan(String value) {
            addCriterion("CREATOR_ID <", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(String value) {
            addCriterion("CREATOR_ID <=", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdLike(String value) {
            addCriterion("CREATOR_ID like", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdNotLike(String value) {
            addCriterion("CREATOR_ID not like", value, "creatorId");
            return this;
        }

        public Criteria andCreatorIdIn(List values) {
            addCriterion("CREATOR_ID in", values, "creatorId");
            return this;
        }

        public Criteria andCreatorIdNotIn(List values) {
            addCriterion("CREATOR_ID not in", values, "creatorId");
            return this;
        }

        public Criteria andCreatorIdBetween(String value1, String value2) {
            addCriterion("CREATOR_ID between", value1, value2, "creatorId");
            return this;
        }

        public Criteria andCreatorIdNotBetween(String value1, String value2) {
            addCriterion("CREATOR_ID not between", value1, value2, "creatorId");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return this;
        }

        public Criteria andStartDateEqualTo(BigDecimal value) {
            addCriterion("START_DATE =", value, "startDate");
            return this;
        }

        public Criteria andStartDateNotEqualTo(BigDecimal value) {
            addCriterion("START_DATE <>", value, "startDate");
            return this;
        }

        public Criteria andStartDateGreaterThan(BigDecimal value) {
            addCriterion("START_DATE >", value, "startDate");
            return this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("START_DATE >=", value, "startDate");
            return this;
        }

        public Criteria andStartDateLessThan(BigDecimal value) {
            addCriterion("START_DATE <", value, "startDate");
            return this;
        }

        public Criteria andStartDateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("START_DATE <=", value, "startDate");
            return this;
        }

        public Criteria andStartDateIn(List values) {
            addCriterion("START_DATE in", values, "startDate");
            return this;
        }

        public Criteria andStartDateNotIn(List values) {
            addCriterion("START_DATE not in", values, "startDate");
            return this;
        }

        public Criteria andStartDateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return this;
        }

        public Criteria andStartDateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return this;
        }

        public Criteria andLateOutMinutesIsNull() {
            addCriterion("LATE_OUT_MINUTES is null");
            return this;
        }

        public Criteria andLateOutMinutesIsNotNull() {
            addCriterion("LATE_OUT_MINUTES is not null");
            return this;
        }

        public Criteria andLateOutMinutesEqualTo(BigDecimal value) {
            addCriterion("LATE_OUT_MINUTES =", value, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesNotEqualTo(BigDecimal value) {
            addCriterion("LATE_OUT_MINUTES <>", value, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesGreaterThan(BigDecimal value) {
            addCriterion("LATE_OUT_MINUTES >", value, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LATE_OUT_MINUTES >=", value, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesLessThan(BigDecimal value) {
            addCriterion("LATE_OUT_MINUTES <", value, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LATE_OUT_MINUTES <=", value, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesIn(List values) {
            addCriterion("LATE_OUT_MINUTES in", values, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesNotIn(List values) {
            addCriterion("LATE_OUT_MINUTES not in", values, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATE_OUT_MINUTES between", value1, value2, "lateOutMinutes");
            return this;
        }

        public Criteria andLateOutMinutesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATE_OUT_MINUTES not between", value1, value2, "lateOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesIsNull() {
            addCriterion("LEAVE_OUT_MINUTES is null");
            return this;
        }

        public Criteria andLeaveOutMinutesIsNotNull() {
            addCriterion("LEAVE_OUT_MINUTES is not null");
            return this;
        }

        public Criteria andLeaveOutMinutesEqualTo(BigDecimal value) {
            addCriterion("LEAVE_OUT_MINUTES =", value, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesNotEqualTo(BigDecimal value) {
            addCriterion("LEAVE_OUT_MINUTES <>", value, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesGreaterThan(BigDecimal value) {
            addCriterion("LEAVE_OUT_MINUTES >", value, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEAVE_OUT_MINUTES >=", value, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesLessThan(BigDecimal value) {
            addCriterion("LEAVE_OUT_MINUTES <", value, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEAVE_OUT_MINUTES <=", value, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesIn(List values) {
            addCriterion("LEAVE_OUT_MINUTES in", values, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesNotIn(List values) {
            addCriterion("LEAVE_OUT_MINUTES not in", values, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEAVE_OUT_MINUTES between", value1, value2, "leaveOutMinutes");
            return this;
        }

        public Criteria andLeaveOutMinutesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEAVE_OUT_MINUTES not between", value1, value2, "leaveOutMinutes");
            return this;
        }

        public Criteria andLateStatIsNull() {
            addCriterion("LATE_STAT is null");
            return this;
        }

        public Criteria andLateStatIsNotNull() {
            addCriterion("LATE_STAT is not null");
            return this;
        }

        public Criteria andLateStatEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT =", value, "lateStat");
            return this;
        }

        public Criteria andLateStatNotEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT <>", value, "lateStat");
            return this;
        }

        public Criteria andLateStatGreaterThan(BigDecimal value) {
            addCriterion("LATE_STAT >", value, "lateStat");
            return this;
        }

        public Criteria andLateStatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT >=", value, "lateStat");
            return this;
        }

        public Criteria andLateStatLessThan(BigDecimal value) {
            addCriterion("LATE_STAT <", value, "lateStat");
            return this;
        }

        public Criteria andLateStatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT <=", value, "lateStat");
            return this;
        }

        public Criteria andLateStatIn(List values) {
            addCriterion("LATE_STAT in", values, "lateStat");
            return this;
        }

        public Criteria andLateStatNotIn(List values) {
            addCriterion("LATE_STAT not in", values, "lateStat");
            return this;
        }

        public Criteria andLateStatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATE_STAT between", value1, value2, "lateStat");
            return this;
        }

        public Criteria andLateStatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATE_STAT not between", value1, value2, "lateStat");
            return this;
        }

        public Criteria andLateStatMinutesIsNull() {
            addCriterion("LATE_STAT_MINUTES is null");
            return this;
        }

        public Criteria andLateStatMinutesIsNotNull() {
            addCriterion("LATE_STAT_MINUTES is not null");
            return this;
        }

        public Criteria andLateStatMinutesEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT_MINUTES =", value, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesNotEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT_MINUTES <>", value, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesGreaterThan(BigDecimal value) {
            addCriterion("LATE_STAT_MINUTES >", value, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT_MINUTES >=", value, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesLessThan(BigDecimal value) {
            addCriterion("LATE_STAT_MINUTES <", value, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LATE_STAT_MINUTES <=", value, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesIn(List values) {
            addCriterion("LATE_STAT_MINUTES in", values, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesNotIn(List values) {
            addCriterion("LATE_STAT_MINUTES not in", values, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATE_STAT_MINUTES between", value1, value2, "lateStatMinutes");
            return this;
        }

        public Criteria andLateStatMinutesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATE_STAT_MINUTES not between", value1, value2, "lateStatMinutes");
            return this;
        }

        public Criteria andLeaveStatIsNull() {
            addCriterion("LEAVE_STAT is null");
            return this;
        }

        public Criteria andLeaveStatIsNotNull() {
            addCriterion("LEAVE_STAT is not null");
            return this;
        }

        public Criteria andLeaveStatEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT =", value, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatNotEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT <>", value, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatGreaterThan(BigDecimal value) {
            addCriterion("LEAVE_STAT >", value, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT >=", value, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatLessThan(BigDecimal value) {
            addCriterion("LEAVE_STAT <", value, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT <=", value, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatIn(List values) {
            addCriterion("LEAVE_STAT in", values, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatNotIn(List values) {
            addCriterion("LEAVE_STAT not in", values, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEAVE_STAT between", value1, value2, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEAVE_STAT not between", value1, value2, "leaveStat");
            return this;
        }

        public Criteria andLeaveStatMinutesIsNull() {
            addCriterion("LEAVE_STAT_MINUTES is null");
            return this;
        }

        public Criteria andLeaveStatMinutesIsNotNull() {
            addCriterion("LEAVE_STAT_MINUTES is not null");
            return this;
        }

        public Criteria andLeaveStatMinutesEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT_MINUTES =", value, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesNotEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT_MINUTES <>", value, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesGreaterThan(BigDecimal value) {
            addCriterion("LEAVE_STAT_MINUTES >", value, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT_MINUTES >=", value, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesLessThan(BigDecimal value) {
            addCriterion("LEAVE_STAT_MINUTES <", value, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEAVE_STAT_MINUTES <=", value, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesIn(List values) {
            addCriterion("LEAVE_STAT_MINUTES in", values, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesNotIn(List values) {
            addCriterion("LEAVE_STAT_MINUTES not in", values, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEAVE_STAT_MINUTES between", value1, value2, "leaveStatMinutes");
            return this;
        }

        public Criteria andLeaveStatMinutesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEAVE_STAT_MINUTES not between", value1, value2, "leaveStatMinutes");
            return this;
        }
    }
}