package com.megaeyes.persistence.ibatis.model;

import java.math.BigDecimal;

public class EpAssets {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.ID
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.TYPE
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private BigDecimal type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.USE_TIME
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private BigDecimal useTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.EXPIRATION_TIME
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private BigDecimal expirationTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.SIGNIFICANT_LEVEL
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private BigDecimal significantLevel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.DEVICE_NUMBER
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private String deviceNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_ASSETS.INSTALL_LOCATION
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private String installLocation;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.ID
     *
     * @return the value of HBDW1.EP_ASSETS.ID
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.ID
     *
     * @param id the value for HBDW1.EP_ASSETS.ID
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.TYPE
     *
     * @return the value of HBDW1.EP_ASSETS.TYPE
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.TYPE
     *
     * @param type the value for HBDW1.EP_ASSETS.TYPE
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.USE_TIME
     *
     * @return the value of HBDW1.EP_ASSETS.USE_TIME
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public BigDecimal getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.USE_TIME
     *
     * @param useTime the value for HBDW1.EP_ASSETS.USE_TIME
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setUseTime(BigDecimal useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.EXPIRATION_TIME
     *
     * @return the value of HBDW1.EP_ASSETS.EXPIRATION_TIME
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public BigDecimal getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.EXPIRATION_TIME
     *
     * @param expirationTime the value for HBDW1.EP_ASSETS.EXPIRATION_TIME
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setExpirationTime(BigDecimal expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.SIGNIFICANT_LEVEL
     *
     * @return the value of HBDW1.EP_ASSETS.SIGNIFICANT_LEVEL
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public BigDecimal getSignificantLevel() {
        return significantLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.SIGNIFICANT_LEVEL
     *
     * @param significantLevel the value for HBDW1.EP_ASSETS.SIGNIFICANT_LEVEL
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setSignificantLevel(BigDecimal significantLevel) {
        this.significantLevel = significantLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.DEVICE_NUMBER
     *
     * @return the value of HBDW1.EP_ASSETS.DEVICE_NUMBER
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.DEVICE_NUMBER
     *
     * @param deviceNumber the value for HBDW1.EP_ASSETS.DEVICE_NUMBER
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_ASSETS.INSTALL_LOCATION
     *
     * @return the value of HBDW1.EP_ASSETS.INSTALL_LOCATION
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public String getInstallLocation() {
        return installLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_ASSETS.INSTALL_LOCATION
     *
     * @param installLocation the value for HBDW1.EP_ASSETS.INSTALL_LOCATION
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void setInstallLocation(String installLocation) {
        this.installLocation = installLocation;
    }
}