package com.megaeyes.persistence.ibatis.model;

public class EpProber {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.CONTROL_SERVER_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String controlServerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.EP_PROBER_TYPE_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String epProberTypeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.CHANNEL_NUMBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Short channelNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.SCHEME
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String scheme;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.NAME
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.NOTE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String note;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.MAX_LIMIT
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer maxLimit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.MIN_LIMIT
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer minLimit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.CYCLE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer cycle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.ADDRESS
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.LENGTH
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String length;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.IS_WARN
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer isWarn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.BOOL_WARN
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer boolWarn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.DATA_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String dataType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.POSITION
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String position;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.REGISTER_REVERSE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer registerReverse;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.PLC_IO_SAVE_CYCLE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private Integer plcIoSaveCycle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.PLC_IO_SAVE_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String plcIoSaveType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.PLC_IO_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String plcIoType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EP_PROBER.ORGAN_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    private String organId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.ID
     *
     * @return the value of EP_PROBER.ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.ID
     *
     * @param id the value for EP_PROBER.ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.CONTROL_SERVER_ID
     *
     * @return the value of EP_PROBER.CONTROL_SERVER_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getControlServerId() {
        return controlServerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.CONTROL_SERVER_ID
     *
     * @param controlServerId the value for EP_PROBER.CONTROL_SERVER_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setControlServerId(String controlServerId) {
        this.controlServerId = controlServerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.EP_PROBER_TYPE_ID
     *
     * @return the value of EP_PROBER.EP_PROBER_TYPE_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getEpProberTypeId() {
        return epProberTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.EP_PROBER_TYPE_ID
     *
     * @param epProberTypeId the value for EP_PROBER.EP_PROBER_TYPE_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setEpProberTypeId(String epProberTypeId) {
        this.epProberTypeId = epProberTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.CHANNEL_NUMBER
     *
     * @return the value of EP_PROBER.CHANNEL_NUMBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Short getChannelNumber() {
        return channelNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.CHANNEL_NUMBER
     *
     * @param channelNumber the value for EP_PROBER.CHANNEL_NUMBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setChannelNumber(Short channelNumber) {
        this.channelNumber = channelNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.SCHEME
     *
     * @return the value of EP_PROBER.SCHEME
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.SCHEME
     *
     * @param scheme the value for EP_PROBER.SCHEME
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.NAME
     *
     * @return the value of EP_PROBER.NAME
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.NAME
     *
     * @param name the value for EP_PROBER.NAME
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.NOTE
     *
     * @return the value of EP_PROBER.NOTE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.NOTE
     *
     * @param note the value for EP_PROBER.NOTE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.MAX_LIMIT
     *
     * @return the value of EP_PROBER.MAX_LIMIT
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getMaxLimit() {
        return maxLimit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.MAX_LIMIT
     *
     * @param maxLimit the value for EP_PROBER.MAX_LIMIT
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setMaxLimit(Integer maxLimit) {
        this.maxLimit = maxLimit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.MIN_LIMIT
     *
     * @return the value of EP_PROBER.MIN_LIMIT
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getMinLimit() {
        return minLimit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.MIN_LIMIT
     *
     * @param minLimit the value for EP_PROBER.MIN_LIMIT
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setMinLimit(Integer minLimit) {
        this.minLimit = minLimit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.CYCLE
     *
     * @return the value of EP_PROBER.CYCLE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.CYCLE
     *
     * @param cycle the value for EP_PROBER.CYCLE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.ADDRESS
     *
     * @return the value of EP_PROBER.ADDRESS
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.ADDRESS
     *
     * @param address the value for EP_PROBER.ADDRESS
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.LENGTH
     *
     * @return the value of EP_PROBER.LENGTH
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.LENGTH
     *
     * @param length the value for EP_PROBER.LENGTH
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setLength(String length) {
        this.length = length;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.IS_WARN
     *
     * @return the value of EP_PROBER.IS_WARN
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getIsWarn() {
        return isWarn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.IS_WARN
     *
     * @param isWarn the value for EP_PROBER.IS_WARN
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setIsWarn(Integer isWarn) {
        this.isWarn = isWarn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.BOOL_WARN
     *
     * @return the value of EP_PROBER.BOOL_WARN
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getBoolWarn() {
        return boolWarn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.BOOL_WARN
     *
     * @param boolWarn the value for EP_PROBER.BOOL_WARN
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setBoolWarn(Integer boolWarn) {
        this.boolWarn = boolWarn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.DATA_TYPE
     *
     * @return the value of EP_PROBER.DATA_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.DATA_TYPE
     *
     * @param dataType the value for EP_PROBER.DATA_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.POSITION
     *
     * @return the value of EP_PROBER.POSITION
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.POSITION
     *
     * @param position the value for EP_PROBER.POSITION
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.REGISTER_REVERSE
     *
     * @return the value of EP_PROBER.REGISTER_REVERSE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getRegisterReverse() {
        return registerReverse;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.REGISTER_REVERSE
     *
     * @param registerReverse the value for EP_PROBER.REGISTER_REVERSE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setRegisterReverse(Integer registerReverse) {
        this.registerReverse = registerReverse;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.PLC_IO_SAVE_CYCLE
     *
     * @return the value of EP_PROBER.PLC_IO_SAVE_CYCLE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public Integer getPlcIoSaveCycle() {
        return plcIoSaveCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.PLC_IO_SAVE_CYCLE
     *
     * @param plcIoSaveCycle the value for EP_PROBER.PLC_IO_SAVE_CYCLE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setPlcIoSaveCycle(Integer plcIoSaveCycle) {
        this.plcIoSaveCycle = plcIoSaveCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.PLC_IO_SAVE_TYPE
     *
     * @return the value of EP_PROBER.PLC_IO_SAVE_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getPlcIoSaveType() {
        return plcIoSaveType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.PLC_IO_SAVE_TYPE
     *
     * @param plcIoSaveType the value for EP_PROBER.PLC_IO_SAVE_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setPlcIoSaveType(String plcIoSaveType) {
        this.plcIoSaveType = plcIoSaveType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.PLC_IO_TYPE
     *
     * @return the value of EP_PROBER.PLC_IO_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getPlcIoType() {
        return plcIoType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.PLC_IO_TYPE
     *
     * @param plcIoType the value for EP_PROBER.PLC_IO_TYPE
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setPlcIoType(String plcIoType) {
        this.plcIoType = plcIoType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EP_PROBER.ORGAN_ID
     *
     * @return the value of EP_PROBER.ORGAN_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EP_PROBER.ORGAN_ID
     *
     * @param organId the value for EP_PROBER.ORGAN_ID
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }
}