package com.megaeyes.persistence.ibatis.model;

public class EpRDoorVic {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_R_DOOR_VIC.ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_R_DOOR_VIC.DOOR_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    private String doorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_R_DOOR_VIC.VIC_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    private String vicId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_R_DOOR_VIC.PRESET_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    private String presetId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_R_DOOR_VIC.ID
     *
     * @return the value of HBDW1.EP_R_DOOR_VIC.ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_R_DOOR_VIC.ID
     *
     * @param id the value for HBDW1.EP_R_DOOR_VIC.ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_R_DOOR_VIC.DOOR_ID
     *
     * @return the value of HBDW1.EP_R_DOOR_VIC.DOOR_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public String getDoorId() {
        return doorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_R_DOOR_VIC.DOOR_ID
     *
     * @param doorId the value for HBDW1.EP_R_DOOR_VIC.DOOR_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public void setDoorId(String doorId) {
        this.doorId = doorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_R_DOOR_VIC.VIC_ID
     *
     * @return the value of HBDW1.EP_R_DOOR_VIC.VIC_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public String getVicId() {
        return vicId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_R_DOOR_VIC.VIC_ID
     *
     * @param vicId the value for HBDW1.EP_R_DOOR_VIC.VIC_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public void setVicId(String vicId) {
        this.vicId = vicId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_R_DOOR_VIC.PRESET_ID
     *
     * @return the value of HBDW1.EP_R_DOOR_VIC.PRESET_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public String getPresetId() {
        return presetId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_R_DOOR_VIC.PRESET_ID
     *
     * @param presetId the value for HBDW1.EP_R_DOOR_VIC.PRESET_ID
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public void setPresetId(String presetId) {
        this.presetId = presetId;
    }
}