package com.megaeyes.persistence.ibatis.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EpRProberVicExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public EpRProberVicExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    protected EpRProberVicExample(EpRProberVicExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_R_PROBER_VIC
     *
     * @abatorgenerated Mon May 14 02:48:24 GMT 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andVicIdIsNull() {
            addCriterion("VIC_ID is null");
            return this;
        }

        public Criteria andVicIdIsNotNull() {
            addCriterion("VIC_ID is not null");
            return this;
        }

        public Criteria andVicIdEqualTo(String value) {
            addCriterion("VIC_ID =", value, "vicId");
            return this;
        }

        public Criteria andVicIdNotEqualTo(String value) {
            addCriterion("VIC_ID <>", value, "vicId");
            return this;
        }

        public Criteria andVicIdGreaterThan(String value) {
            addCriterion("VIC_ID >", value, "vicId");
            return this;
        }

        public Criteria andVicIdGreaterThanOrEqualTo(String value) {
            addCriterion("VIC_ID >=", value, "vicId");
            return this;
        }

        public Criteria andVicIdLessThan(String value) {
            addCriterion("VIC_ID <", value, "vicId");
            return this;
        }

        public Criteria andVicIdLessThanOrEqualTo(String value) {
            addCriterion("VIC_ID <=", value, "vicId");
            return this;
        }

        public Criteria andVicIdLike(String value) {
            addCriterion("VIC_ID like", value, "vicId");
            return this;
        }

        public Criteria andVicIdNotLike(String value) {
            addCriterion("VIC_ID not like", value, "vicId");
            return this;
        }

        public Criteria andVicIdIn(List values) {
            addCriterion("VIC_ID in", values, "vicId");
            return this;
        }

        public Criteria andVicIdNotIn(List values) {
            addCriterion("VIC_ID not in", values, "vicId");
            return this;
        }

        public Criteria andVicIdBetween(String value1, String value2) {
            addCriterion("VIC_ID between", value1, value2, "vicId");
            return this;
        }

        public Criteria andVicIdNotBetween(String value1, String value2) {
            addCriterion("VIC_ID not between", value1, value2, "vicId");
            return this;
        }

        public Criteria andProberIdIsNull() {
            addCriterion("PROBER_ID is null");
            return this;
        }

        public Criteria andProberIdIsNotNull() {
            addCriterion("PROBER_ID is not null");
            return this;
        }

        public Criteria andProberIdEqualTo(String value) {
            addCriterion("PROBER_ID =", value, "proberId");
            return this;
        }

        public Criteria andProberIdNotEqualTo(String value) {
            addCriterion("PROBER_ID <>", value, "proberId");
            return this;
        }

        public Criteria andProberIdGreaterThan(String value) {
            addCriterion("PROBER_ID >", value, "proberId");
            return this;
        }

        public Criteria andProberIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROBER_ID >=", value, "proberId");
            return this;
        }

        public Criteria andProberIdLessThan(String value) {
            addCriterion("PROBER_ID <", value, "proberId");
            return this;
        }

        public Criteria andProberIdLessThanOrEqualTo(String value) {
            addCriterion("PROBER_ID <=", value, "proberId");
            return this;
        }

        public Criteria andProberIdLike(String value) {
            addCriterion("PROBER_ID like", value, "proberId");
            return this;
        }

        public Criteria andProberIdNotLike(String value) {
            addCriterion("PROBER_ID not like", value, "proberId");
            return this;
        }

        public Criteria andProberIdIn(List values) {
            addCriterion("PROBER_ID in", values, "proberId");
            return this;
        }

        public Criteria andProberIdNotIn(List values) {
            addCriterion("PROBER_ID not in", values, "proberId");
            return this;
        }

        public Criteria andProberIdBetween(String value1, String value2) {
            addCriterion("PROBER_ID between", value1, value2, "proberId");
            return this;
        }

        public Criteria andProberIdNotBetween(String value1, String value2) {
            addCriterion("PROBER_ID not between", value1, value2, "proberId");
            return this;
        }

        public Criteria andPresetIdIsNull() {
            addCriterion("PRESET_ID is null");
            return this;
        }

        public Criteria andPresetIdIsNotNull() {
            addCriterion("PRESET_ID is not null");
            return this;
        }

        public Criteria andPresetIdEqualTo(String value) {
            addCriterion("PRESET_ID =", value, "presetId");
            return this;
        }

        public Criteria andPresetIdNotEqualTo(String value) {
            addCriterion("PRESET_ID <>", value, "presetId");
            return this;
        }

        public Criteria andPresetIdGreaterThan(String value) {
            addCriterion("PRESET_ID >", value, "presetId");
            return this;
        }

        public Criteria andPresetIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRESET_ID >=", value, "presetId");
            return this;
        }

        public Criteria andPresetIdLessThan(String value) {
            addCriterion("PRESET_ID <", value, "presetId");
            return this;
        }

        public Criteria andPresetIdLessThanOrEqualTo(String value) {
            addCriterion("PRESET_ID <=", value, "presetId");
            return this;
        }

        public Criteria andPresetIdLike(String value) {
            addCriterion("PRESET_ID like", value, "presetId");
            return this;
        }

        public Criteria andPresetIdNotLike(String value) {
            addCriterion("PRESET_ID not like", value, "presetId");
            return this;
        }

        public Criteria andPresetIdIn(List values) {
            addCriterion("PRESET_ID in", values, "presetId");
            return this;
        }

        public Criteria andPresetIdNotIn(List values) {
            addCriterion("PRESET_ID not in", values, "presetId");
            return this;
        }

        public Criteria andPresetIdBetween(String value1, String value2) {
            addCriterion("PRESET_ID between", value1, value2, "presetId");
            return this;
        }

        public Criteria andPresetIdNotBetween(String value1, String value2) {
            addCriterion("PRESET_ID not between", value1, value2, "presetId");
            return this;
        }
    }
}