package com.megaeyes.persistence.ibatis.model;

public class EpScheme {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_SCHEME.ID
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_SCHEME.NAME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_SCHEME.ORGAN_ID
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private String organId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_SCHEME.NOTE
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private String note;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_SCHEME.TYPE
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_SCHEME.LAST_UPDATE_TIME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private Long lastUpdateTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_SCHEME.ID
     *
     * @return the value of HBDW1.EP_SCHEME.ID
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_SCHEME.ID
     *
     * @param id the value for HBDW1.EP_SCHEME.ID
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_SCHEME.NAME
     *
     * @return the value of HBDW1.EP_SCHEME.NAME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_SCHEME.NAME
     *
     * @param name the value for HBDW1.EP_SCHEME.NAME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_SCHEME.ORGAN_ID
     *
     * @return the value of HBDW1.EP_SCHEME.ORGAN_ID
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_SCHEME.ORGAN_ID
     *
     * @param organId the value for HBDW1.EP_SCHEME.ORGAN_ID
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_SCHEME.NOTE
     *
     * @return the value of HBDW1.EP_SCHEME.NOTE
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_SCHEME.NOTE
     *
     * @param note the value for HBDW1.EP_SCHEME.NOTE
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_SCHEME.TYPE
     *
     * @return the value of HBDW1.EP_SCHEME.TYPE
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_SCHEME.TYPE
     *
     * @param type the value for HBDW1.EP_SCHEME.TYPE
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_SCHEME.LAST_UPDATE_TIME
     *
     * @return the value of HBDW1.EP_SCHEME.LAST_UPDATE_TIME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public Long getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_SCHEME.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for HBDW1.EP_SCHEME.LAST_UPDATE_TIME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}