package com.megaeyes.persistence.ibatis.model;

public class EpTaskStep {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_TASK_STEP.ID
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_TASK_STEP.NAME
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_TASK_STEP.SEQ
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private Integer seq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_TASK_STEP.TASK_ID
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private String taskId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_TASK_STEP.NOTE
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private String note;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column HBDW1.EP_TASK_STEP.DEVICE_TYPE
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private String deviceType;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_TASK_STEP.ID
     *
     * @return the value of HBDW1.EP_TASK_STEP.ID
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_TASK_STEP.ID
     *
     * @param id the value for HBDW1.EP_TASK_STEP.ID
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_TASK_STEP.NAME
     *
     * @return the value of HBDW1.EP_TASK_STEP.NAME
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_TASK_STEP.NAME
     *
     * @param name the value for HBDW1.EP_TASK_STEP.NAME
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_TASK_STEP.SEQ
     *
     * @return the value of HBDW1.EP_TASK_STEP.SEQ
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_TASK_STEP.SEQ
     *
     * @param seq the value for HBDW1.EP_TASK_STEP.SEQ
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_TASK_STEP.TASK_ID
     *
     * @return the value of HBDW1.EP_TASK_STEP.TASK_ID
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_TASK_STEP.TASK_ID
     *
     * @param taskId the value for HBDW1.EP_TASK_STEP.TASK_ID
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_TASK_STEP.NOTE
     *
     * @return the value of HBDW1.EP_TASK_STEP.NOTE
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_TASK_STEP.NOTE
     *
     * @param note the value for HBDW1.EP_TASK_STEP.NOTE
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column HBDW1.EP_TASK_STEP.DEVICE_TYPE
     *
     * @return the value of HBDW1.EP_TASK_STEP.DEVICE_TYPE
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column HBDW1.EP_TASK_STEP.DEVICE_TYPE
     *
     * @param deviceType the value for HBDW1.EP_TASK_STEP.DEVICE_TYPE
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }
}