package com.megaeyes.persistence.ibatis.model;

public class HistoryVideo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.ID
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.VIC_ID
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private String vicId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_NAME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private String fileName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.PLAY_URL
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private String playUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.BEGIN_TIME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private Long beginTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.END_TIME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private Long endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_SIZE
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private Long fileSize;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.DECODER_TAG
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private String decoderTag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.TYPE
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    private String type;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.ID
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.ID
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.ID
     *
     * @param id the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.ID
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.VIC_ID
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.VIC_ID
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public String getVicId() {
        return vicId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.VIC_ID
     *
     * @param vicId the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.VIC_ID
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setVicId(String vicId) {
        this.vicId = vicId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_NAME
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_NAME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_NAME
     *
     * @param fileName the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_NAME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.PLAY_URL
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.PLAY_URL
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public String getPlayUrl() {
        return playUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.PLAY_URL
     *
     * @param playUrl the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.PLAY_URL
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setPlayUrl(String playUrl) {
        this.playUrl = playUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.BEGIN_TIME
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.BEGIN_TIME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public Long getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.BEGIN_TIME
     *
     * @param beginTime the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.BEGIN_TIME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setBeginTime(Long beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.END_TIME
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.END_TIME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.END_TIME
     *
     * @param endTime the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.END_TIME
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_SIZE
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_SIZE
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_SIZE
     *
     * @param fileSize the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.FILE_SIZE
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.DECODER_TAG
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.DECODER_TAG
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public String getDecoderTag() {
        return decoderTag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.DECODER_TAG
     *
     * @param decoderTag the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.DECODER_TAG
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setDecoderTag(String decoderTag) {
        this.decoderTag = decoderTag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.TYPE
     *
     * @return the value of JHDYJDBMEGAJQ33.HISTORY_VIDEO.TYPE
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.HISTORY_VIDEO.TYPE
     *
     * @param type the value for JHDYJDBMEGAJQ33.HISTORY_VIDEO.TYPE
     *
     * @abatorgenerated Tue May 15 09:26:46 CST 2012
     */
    public void setType(String type) {
        this.type = type;
    }
}