package com.megaeyes.persistence.ibatis.model;

import java.math.BigDecimal;

public class VideoInputServer {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.OPTIMISTIC_LOCK
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal optimisticLock;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.F_NAME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAMING
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String naming;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.INSTALL_LOCATION
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String installLocation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NOTE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String note;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.DEVICE_NUMBER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String deviceNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IP
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String ip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.LINK_TYPE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String linkType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.HEART_CYCLE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Long heartCycle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_TIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String rebootTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_CYCLE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Long rebootCycle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_CONNECT_AMOUNT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Long maxConnectAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INTPUT_AMOUNT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Long videoIntputAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INPUT_SERVER_MODEL_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String videoInputServerModelId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.COMPANY_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String companyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.STD_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String stdId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_SCHEME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Short isSupportScheme;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.O_ORGAN_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String organId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_VIDEOINPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal maxVideoinputChannel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMOUTPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal maxAlarmoutputChannel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMINPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal maxAlarminputChannel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUSPENDED
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Short isSuspended;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_NAT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Short isSupportNat;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_VOD2
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Short isSupportVod2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_PTZ_LOCK
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Short isSupportPtzLock;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.CREATETIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal createtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.START_ONLINE_TIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal startOnlineTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_REGISTERD
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal isRegisterd;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.WEB_PORT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private BigDecimal webPort;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAT_IP
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String natIp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_NAT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Short isNat;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SUPPORT_CAPACITY
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String supportCapacity;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIS_TYPE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String visType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.PASSWORD
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SIP_PORT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private Integer sipPort;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.ID
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.ID
     *
     * @param id the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.OPTIMISTIC_LOCK
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.OPTIMISTIC_LOCK
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getOptimisticLock() {
        return optimisticLock;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.OPTIMISTIC_LOCK
     *
     * @param optimisticLock the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.OPTIMISTIC_LOCK
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setOptimisticLock(BigDecimal optimisticLock) {
        this.optimisticLock = optimisticLock;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.F_NAME
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.F_NAME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.F_NAME
     *
     * @param name the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.F_NAME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAMING
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAMING
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getNaming() {
        return naming;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAMING
     *
     * @param naming the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAMING
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setNaming(String naming) {
        this.naming = naming;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.INSTALL_LOCATION
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.INSTALL_LOCATION
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getInstallLocation() {
        return installLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.INSTALL_LOCATION
     *
     * @param installLocation the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.INSTALL_LOCATION
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setInstallLocation(String installLocation) {
        this.installLocation = installLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NOTE
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NOTE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NOTE
     *
     * @param note the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NOTE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.DEVICE_NUMBER
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.DEVICE_NUMBER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.DEVICE_NUMBER
     *
     * @param deviceNumber the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.DEVICE_NUMBER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IP
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IP
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IP
     *
     * @param ip the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IP
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.LINK_TYPE
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.LINK_TYPE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.LINK_TYPE
     *
     * @param linkType the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.LINK_TYPE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setLinkType(String linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.HEART_CYCLE
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.HEART_CYCLE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Long getHeartCycle() {
        return heartCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.HEART_CYCLE
     *
     * @param heartCycle the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.HEART_CYCLE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setHeartCycle(Long heartCycle) {
        this.heartCycle = heartCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_TIME
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_TIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getRebootTime() {
        return rebootTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_TIME
     *
     * @param rebootTime the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_TIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setRebootTime(String rebootTime) {
        this.rebootTime = rebootTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_CYCLE
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_CYCLE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Long getRebootCycle() {
        return rebootCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_CYCLE
     *
     * @param rebootCycle the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.REBOOT_CYCLE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setRebootCycle(Long rebootCycle) {
        this.rebootCycle = rebootCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_CONNECT_AMOUNT
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_CONNECT_AMOUNT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Long getMaxConnectAmount() {
        return maxConnectAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_CONNECT_AMOUNT
     *
     * @param maxConnectAmount the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_CONNECT_AMOUNT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setMaxConnectAmount(Long maxConnectAmount) {
        this.maxConnectAmount = maxConnectAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INTPUT_AMOUNT
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INTPUT_AMOUNT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Long getVideoIntputAmount() {
        return videoIntputAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INTPUT_AMOUNT
     *
     * @param videoIntputAmount the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INTPUT_AMOUNT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setVideoIntputAmount(Long videoIntputAmount) {
        this.videoIntputAmount = videoIntputAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INPUT_SERVER_MODEL_ID
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INPUT_SERVER_MODEL_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getVideoInputServerModelId() {
        return videoInputServerModelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INPUT_SERVER_MODEL_ID
     *
     * @param videoInputServerModelId the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIDEO_INPUT_SERVER_MODEL_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setVideoInputServerModelId(String videoInputServerModelId) {
        this.videoInputServerModelId = videoInputServerModelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.COMPANY_ID
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.COMPANY_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.COMPANY_ID
     *
     * @param companyId the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.COMPANY_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.STD_ID
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.STD_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getStdId() {
        return stdId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.STD_ID
     *
     * @param stdId the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.STD_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setStdId(String stdId) {
        this.stdId = stdId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_SCHEME
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_SCHEME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Short getIsSupportScheme() {
        return isSupportScheme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_SCHEME
     *
     * @param isSupportScheme the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_SCHEME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsSupportScheme(Short isSupportScheme) {
        this.isSupportScheme = isSupportScheme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.O_ORGAN_ID
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.O_ORGAN_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.O_ORGAN_ID
     *
     * @param organId the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.O_ORGAN_ID
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_VIDEOINPUT_CHANNEL
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_VIDEOINPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getMaxVideoinputChannel() {
        return maxVideoinputChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_VIDEOINPUT_CHANNEL
     *
     * @param maxVideoinputChannel the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_VIDEOINPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setMaxVideoinputChannel(BigDecimal maxVideoinputChannel) {
        this.maxVideoinputChannel = maxVideoinputChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMOUTPUT_CHANNEL
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMOUTPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getMaxAlarmoutputChannel() {
        return maxAlarmoutputChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMOUTPUT_CHANNEL
     *
     * @param maxAlarmoutputChannel the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMOUTPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setMaxAlarmoutputChannel(BigDecimal maxAlarmoutputChannel) {
        this.maxAlarmoutputChannel = maxAlarmoutputChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMINPUT_CHANNEL
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMINPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getMaxAlarminputChannel() {
        return maxAlarminputChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMINPUT_CHANNEL
     *
     * @param maxAlarminputChannel the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.MAX_ALARMINPUT_CHANNEL
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setMaxAlarminputChannel(BigDecimal maxAlarminputChannel) {
        this.maxAlarminputChannel = maxAlarminputChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUSPENDED
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUSPENDED
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Short getIsSuspended() {
        return isSuspended;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUSPENDED
     *
     * @param isSuspended the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUSPENDED
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsSuspended(Short isSuspended) {
        this.isSuspended = isSuspended;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_NAT
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_NAT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Short getIsSupportNat() {
        return isSupportNat;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_NAT
     *
     * @param isSupportNat the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_NAT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsSupportNat(Short isSupportNat) {
        this.isSupportNat = isSupportNat;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_VOD2
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_VOD2
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Short getIsSupportVod2() {
        return isSupportVod2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_VOD2
     *
     * @param isSupportVod2 the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_VOD2
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsSupportVod2(Short isSupportVod2) {
        this.isSupportVod2 = isSupportVod2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_PTZ_LOCK
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_PTZ_LOCK
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Short getIsSupportPtzLock() {
        return isSupportPtzLock;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_PTZ_LOCK
     *
     * @param isSupportPtzLock the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_SUPPORT_PTZ_LOCK
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsSupportPtzLock(Short isSupportPtzLock) {
        this.isSupportPtzLock = isSupportPtzLock;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.CREATETIME
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.CREATETIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.CREATETIME
     *
     * @param createtime the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.CREATETIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setCreatetime(BigDecimal createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.START_ONLINE_TIME
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.START_ONLINE_TIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getStartOnlineTime() {
        return startOnlineTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.START_ONLINE_TIME
     *
     * @param startOnlineTime the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.START_ONLINE_TIME
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setStartOnlineTime(BigDecimal startOnlineTime) {
        this.startOnlineTime = startOnlineTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_REGISTERD
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_REGISTERD
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getIsRegisterd() {
        return isRegisterd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_REGISTERD
     *
     * @param isRegisterd the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_REGISTERD
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsRegisterd(BigDecimal isRegisterd) {
        this.isRegisterd = isRegisterd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.WEB_PORT
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.WEB_PORT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public BigDecimal getWebPort() {
        return webPort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.WEB_PORT
     *
     * @param webPort the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.WEB_PORT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setWebPort(BigDecimal webPort) {
        this.webPort = webPort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAT_IP
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAT_IP
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getNatIp() {
        return natIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAT_IP
     *
     * @param natIp the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.NAT_IP
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setNatIp(String natIp) {
        this.natIp = natIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_NAT
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_NAT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Short getIsNat() {
        return isNat;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_NAT
     *
     * @param isNat the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.IS_NAT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setIsNat(Short isNat) {
        this.isNat = isNat;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SUPPORT_CAPACITY
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SUPPORT_CAPACITY
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getSupportCapacity() {
        return supportCapacity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SUPPORT_CAPACITY
     *
     * @param supportCapacity the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SUPPORT_CAPACITY
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setSupportCapacity(String supportCapacity) {
        this.supportCapacity = supportCapacity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIS_TYPE
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIS_TYPE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getVisType() {
        return visType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIS_TYPE
     *
     * @param visType the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.VIS_TYPE
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setVisType(String visType) {
        this.visType = visType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.PASSWORD
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.PASSWORD
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.PASSWORD
     *
     * @param password the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.PASSWORD
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SIP_PORT
     *
     * @return the value of JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SIP_PORT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public Integer getSipPort() {
        return sipPort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SIP_PORT
     *
     * @param sipPort the value for JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER.SIP_PORT
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void setSipPort(Integer sipPort) {
        this.sipPort = sipPort;
    }
}