package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcAccessControls;
import com.megaeyes.persistence.ibatis.model.AcAccessControlsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcAccessControlsDAOImpl extends SqlMapClientDaoSupport implements AcAccessControlsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public AcAccessControlsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public void insert(AcAccessControls record) {
        getSqlMapClientTemplate().insert("AC_ACCESS_CONTROLS.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int updateByPrimaryKey(AcAccessControls record) {
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_CONTROLS.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int updateByPrimaryKeySelective(AcAccessControls record) {
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_CONTROLS.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public List selectByExample(AcAccessControlsExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_ACCESS_CONTROLS.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public AcAccessControls selectByPrimaryKey(String id) {
        AcAccessControls key = new AcAccessControls();
        key.setId(id);
        AcAccessControls record = (AcAccessControls) getSqlMapClientTemplate().queryForObject("AC_ACCESS_CONTROLS.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int deleteByExample(AcAccessControlsExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_ACCESS_CONTROLS.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        AcAccessControls key = new AcAccessControls();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_ACCESS_CONTROLS.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int countByExample(AcAccessControlsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_ACCESS_CONTROLS.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int updateByExampleSelective(AcAccessControls record, AcAccessControlsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_CONTROLS.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    public int updateByExample(AcAccessControls record, AcAccessControlsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_CONTROLS.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.AC_ACCESS_CONTROLS
     *
     * @abatorgenerated Mon Jun 25 07:06:29 GMT 2012
     */
    private static class UpdateByExampleParms extends AcAccessControlsExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcAccessControlsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}