package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcAccessServers;
import com.megaeyes.persistence.ibatis.model.AcAccessServersExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcAccessServersDAOImpl extends SqlMapClientDaoSupport implements AcAccessServersDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public AcAccessServersDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public void insert(AcAccessServers record) {
        getSqlMapClientTemplate().insert("AC_ACCESS_SERVERS.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int updateByPrimaryKey(AcAccessServers record) {
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_SERVERS.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int updateByPrimaryKeySelective(AcAccessServers record) {
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_SERVERS.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public List selectByExample(AcAccessServersExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_ACCESS_SERVERS.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public AcAccessServers selectByPrimaryKey(String id) {
        AcAccessServers key = new AcAccessServers();
        key.setId(id);
        AcAccessServers record = (AcAccessServers) getSqlMapClientTemplate().queryForObject("AC_ACCESS_SERVERS.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int deleteByExample(AcAccessServersExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_ACCESS_SERVERS.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        AcAccessServers key = new AcAccessServers();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_ACCESS_SERVERS.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int countByExample(AcAccessServersExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_ACCESS_SERVERS.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int updateByExampleSelective(AcAccessServers record, AcAccessServersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_SERVERS.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    public int updateByExample(AcAccessServers record, AcAccessServersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_ACCESS_SERVERS.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.AC_ACCESS_SERVERS
     *
     * @abatorgenerated Mon May 14 07:51:16 GMT 2012
     */
    private static class UpdateByExampleParms extends AcAccessServersExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcAccessServersExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}