package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcAttendanceCheckRecord;
import com.megaeyes.persistence.ibatis.model.AcAttendanceCheckRecordExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcAttendanceCheckRecordDAOImpl extends SqlMapClientDaoSupport implements AcAttendanceCheckRecordDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public AcAttendanceCheckRecordDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public void insert(AcAttendanceCheckRecord record) {
        getSqlMapClientTemplate().insert("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int updateByPrimaryKey(AcAttendanceCheckRecord record) {
        int rows = getSqlMapClientTemplate().update("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int updateByPrimaryKeySelective(AcAttendanceCheckRecord record) {
        int rows = getSqlMapClientTemplate().update("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public List selectByExample(AcAttendanceCheckRecordExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public AcAttendanceCheckRecord selectByPrimaryKey(String id) {
        AcAttendanceCheckRecord key = new AcAttendanceCheckRecord();
        key.setId(id);
        AcAttendanceCheckRecord record = (AcAttendanceCheckRecord) getSqlMapClientTemplate().queryForObject("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int deleteByExample(AcAttendanceCheckRecordExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcAttendanceCheckRecord key = new AcAttendanceCheckRecord();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int countByExample(AcAttendanceCheckRecordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int updateByExampleSelective(AcAttendanceCheckRecord record, AcAttendanceCheckRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    public int updateByExample(AcAttendanceCheckRecord record, AcAttendanceCheckRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_ATTENDANCE_CHECK_RECORD.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_ATTENDANCE_CHECK_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:13:29 CST 2013
     */
    private static class UpdateByExampleParms extends AcAttendanceCheckRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcAttendanceCheckRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}