package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcEmployeeAbsenceRecord;
import com.megaeyes.persistence.ibatis.model.AcEmployeeAbsenceRecordExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcEmployeeAbsenceRecordDAOImpl extends SqlMapClientDaoSupport implements AcEmployeeAbsenceRecordDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public AcEmployeeAbsenceRecordDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public void insert(AcEmployeeAbsenceRecord record) {
        getSqlMapClientTemplate().insert("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int updateByPrimaryKey(AcEmployeeAbsenceRecord record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int updateByPrimaryKeySelective(AcEmployeeAbsenceRecord record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public List selectByExample(AcEmployeeAbsenceRecordExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public AcEmployeeAbsenceRecord selectByPrimaryKey(String id) {
        AcEmployeeAbsenceRecord key = new AcEmployeeAbsenceRecord();
        key.setId(id);
        AcEmployeeAbsenceRecord record = (AcEmployeeAbsenceRecord) getSqlMapClientTemplate().queryForObject("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int deleteByExample(AcEmployeeAbsenceRecordExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcEmployeeAbsenceRecord key = new AcEmployeeAbsenceRecord();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int countByExample(AcEmployeeAbsenceRecordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int updateByExampleSelective(AcEmployeeAbsenceRecord record, AcEmployeeAbsenceRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    public int updateByExample(AcEmployeeAbsenceRecord record, AcEmployeeAbsenceRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_ABSENCE_RECORD.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_EMPLOYEE_ABSENCE_RECORD
     *
     * @abatorgenerated Mon Mar 04 14:26:20 CST 2013
     */
    private static class UpdateByExampleParms extends AcEmployeeAbsenceRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcEmployeeAbsenceRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}