package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcEmployeeSchedule;
import com.megaeyes.persistence.ibatis.model.AcEmployeeScheduleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcEmployeeScheduleDAOImpl extends SqlMapClientDaoSupport implements AcEmployeeScheduleDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public AcEmployeeScheduleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public void insert(AcEmployeeSchedule record) {
        getSqlMapClientTemplate().insert("AC_EMPLOYEE_SCHEDULE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int updateByPrimaryKey(AcEmployeeSchedule record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_SCHEDULE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int updateByPrimaryKeySelective(AcEmployeeSchedule record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_SCHEDULE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public List selectByExample(AcEmployeeScheduleExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_EMPLOYEE_SCHEDULE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public AcEmployeeSchedule selectByPrimaryKey(String id) {
        AcEmployeeSchedule key = new AcEmployeeSchedule();
        key.setId(id);
        AcEmployeeSchedule record = (AcEmployeeSchedule) getSqlMapClientTemplate().queryForObject("AC_EMPLOYEE_SCHEDULE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int deleteByExample(AcEmployeeScheduleExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_EMPLOYEE_SCHEDULE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcEmployeeSchedule key = new AcEmployeeSchedule();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_EMPLOYEE_SCHEDULE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int countByExample(AcEmployeeScheduleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_EMPLOYEE_SCHEDULE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int updateByExampleSelective(AcEmployeeSchedule record, AcEmployeeScheduleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_SCHEDULE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    public int updateByExample(AcEmployeeSchedule record, AcEmployeeScheduleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEE_SCHEDULE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_EMPLOYEE_SCHEDULE
     *
     * @abatorgenerated Wed Feb 27 11:04:45 CST 2013
     */
    private static class UpdateByExampleParms extends AcEmployeeScheduleExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcEmployeeScheduleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}