package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcEmployees;
import com.megaeyes.persistence.ibatis.model.AcEmployeesExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcEmployeesDAOImpl extends SqlMapClientDaoSupport implements AcEmployeesDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public AcEmployeesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public void insert(AcEmployees record) {
        getSqlMapClientTemplate().insert("AC_EMPLOYEES.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int updateByPrimaryKeyWithoutBLOBs(AcEmployees record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEES.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int updateByPrimaryKeyWithBLOBs(AcEmployees record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEES.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int updateByPrimaryKeySelective(AcEmployees record) {
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEES.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public List selectByExampleWithoutBLOBs(AcEmployeesExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_EMPLOYEES.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public List selectByExampleWithBLOBs(AcEmployeesExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_EMPLOYEES.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public AcEmployees selectByPrimaryKey(String id) {
        AcEmployees key = new AcEmployees();
        key.setId(id);
        AcEmployees record = (AcEmployees) getSqlMapClientTemplate().queryForObject("AC_EMPLOYEES.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int deleteByExample(AcEmployeesExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_EMPLOYEES.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        AcEmployees key = new AcEmployees();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_EMPLOYEES.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int countByExample(AcEmployeesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_EMPLOYEES.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int updateByExampleSelective(AcEmployees record, AcEmployeesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEES.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int updateByExampleWithBLOBs(AcEmployees record, AcEmployeesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEES.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    public int updateByExampleWithoutBLOBs(AcEmployees record, AcEmployeesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_EMPLOYEES.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.AC_EMPLOYEES
     *
     * @abatorgenerated Wed May 16 15:23:56 CST 2012
     */
    private static class UpdateByExampleParms extends AcEmployeesExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcEmployeesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}