package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcGateway;
import com.megaeyes.persistence.ibatis.model.AcGatewayExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcGatewayDAOImpl extends SqlMapClientDaoSupport implements AcGatewayDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public AcGatewayDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public void insert(AcGateway record) {
        getSqlMapClientTemplate().insert("AC_GATEWAY.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int updateByPrimaryKey(AcGateway record) {
        int rows = getSqlMapClientTemplate().update("AC_GATEWAY.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int updateByPrimaryKeySelective(AcGateway record) {
        int rows = getSqlMapClientTemplate().update("AC_GATEWAY.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public List selectByExample(AcGatewayExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_GATEWAY.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public AcGateway selectByPrimaryKey(String id) {
        AcGateway key = new AcGateway();
        key.setId(id);
        AcGateway record = (AcGateway) getSqlMapClientTemplate().queryForObject("AC_GATEWAY.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int deleteByExample(AcGatewayExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_GATEWAY.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcGateway key = new AcGateway();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_GATEWAY.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int countByExample(AcGatewayExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_GATEWAY.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int updateByExampleSelective(AcGateway record, AcGatewayExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_GATEWAY.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    public int updateByExample(AcGateway record, AcGatewayExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_GATEWAY.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table DL25.AC_GATEWAY
     *
     * @abatorgenerated Mon Jan 21 16:30:30 CST 2013
     */
    private static class UpdateByExampleParms extends AcGatewayExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcGatewayExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}