package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcLog;
import com.megaeyes.persistence.ibatis.model.AcLogExample;
import java.util.List;

public interface AcLogDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    void insert(AcLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int updateByPrimaryKey(AcLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int updateByPrimaryKeySelective(AcLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    List selectByExample(AcLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    AcLog selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int deleteByExample(AcLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int countByExample(AcLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int updateByExampleSelective(AcLog record, AcLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_LOG
     *
     * @abatorgenerated Fri May 25 16:52:11 CST 2012
     */
    int updateByExample(AcLog record, AcLogExample example);
}