package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcRDoorCard;
import com.megaeyes.persistence.ibatis.model.AcRDoorCardExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcRDoorCardDAOImpl extends SqlMapClientDaoSupport implements AcRDoorCardDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public AcRDoorCardDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public void insert(AcRDoorCard record) {
        getSqlMapClientTemplate().insert("AC_R_DOOR_CARD.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int updateByPrimaryKey(AcRDoorCard record) {
        int rows = getSqlMapClientTemplate().update("AC_R_DOOR_CARD.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int updateByPrimaryKeySelective(AcRDoorCard record) {
        int rows = getSqlMapClientTemplate().update("AC_R_DOOR_CARD.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public List selectByExample(AcRDoorCardExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_R_DOOR_CARD.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public AcRDoorCard selectByPrimaryKey(String id) {
        AcRDoorCard key = new AcRDoorCard();
        key.setId(id);
        AcRDoorCard record = (AcRDoorCard) getSqlMapClientTemplate().queryForObject("AC_R_DOOR_CARD.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int deleteByExample(AcRDoorCardExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_R_DOOR_CARD.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        AcRDoorCard key = new AcRDoorCard();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_R_DOOR_CARD.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int countByExample(AcRDoorCardExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_R_DOOR_CARD.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int updateByExampleSelective(AcRDoorCard record, AcRDoorCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_R_DOOR_CARD.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    public int updateByExample(AcRDoorCard record, AcRDoorCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_R_DOOR_CARD.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.AC_R_DOOR_CARD
     *
     * @abatorgenerated Wed May 16 09:36:07 GMT 2012
     */
    private static class UpdateByExampleParms extends AcRDoorCardExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcRDoorCardExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}