package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcREmployeeCard;
import com.megaeyes.persistence.ibatis.model.AcREmployeeCardExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcREmployeeCardDAOImpl extends SqlMapClientDaoSupport implements AcREmployeeCardDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public AcREmployeeCardDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public void insert(AcREmployeeCard record) {
        getSqlMapClientTemplate().insert("AC_R_EMPLOYEE_CARD.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int updateByPrimaryKey(AcREmployeeCard record) {
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_CARD.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int updateByPrimaryKeySelective(AcREmployeeCard record) {
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_CARD.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public List selectByExample(AcREmployeeCardExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_R_EMPLOYEE_CARD.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public AcREmployeeCard selectByPrimaryKey(String id) {
        AcREmployeeCard key = new AcREmployeeCard();
        key.setId(id);
        AcREmployeeCard record = (AcREmployeeCard) getSqlMapClientTemplate().queryForObject("AC_R_EMPLOYEE_CARD.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int deleteByExample(AcREmployeeCardExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_R_EMPLOYEE_CARD.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        AcREmployeeCard key = new AcREmployeeCard();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_R_EMPLOYEE_CARD.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int countByExample(AcREmployeeCardExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_R_EMPLOYEE_CARD.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int updateByExampleSelective(AcREmployeeCard record, AcREmployeeCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_CARD.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    public int updateByExample(AcREmployeeCard record, AcREmployeeCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_CARD.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.AC_R_EMPLOYEE_CARD
     *
     * @abatorgenerated Fri May 18 01:49:30 GMT 2012
     */
    private static class UpdateByExampleParms extends AcREmployeeCardExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcREmployeeCardExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}