package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcREmployeeGroup;
import com.megaeyes.persistence.ibatis.model.AcREmployeeGroupExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcREmployeeGroupDAOImpl extends SqlMapClientDaoSupport implements AcREmployeeGroupDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public AcREmployeeGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public void insert(AcREmployeeGroup record) {
        getSqlMapClientTemplate().insert("AC_R_EMPLOYEE_GROUP.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int updateByPrimaryKey(AcREmployeeGroup record) {
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_GROUP.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int updateByPrimaryKeySelective(AcREmployeeGroup record) {
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_GROUP.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public List selectByExample(AcREmployeeGroupExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_R_EMPLOYEE_GROUP.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public AcREmployeeGroup selectByPrimaryKey(String id) {
        AcREmployeeGroup key = new AcREmployeeGroup();
        key.setId(id);
        AcREmployeeGroup record = (AcREmployeeGroup) getSqlMapClientTemplate().queryForObject("AC_R_EMPLOYEE_GROUP.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int deleteByExample(AcREmployeeGroupExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_R_EMPLOYEE_GROUP.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcREmployeeGroup key = new AcREmployeeGroup();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_R_EMPLOYEE_GROUP.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int countByExample(AcREmployeeGroupExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_R_EMPLOYEE_GROUP.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int updateByExampleSelective(AcREmployeeGroup record, AcREmployeeGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_GROUP.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    public int updateByExample(AcREmployeeGroup record, AcREmployeeGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_R_EMPLOYEE_GROUP.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_R_EMPLOYEE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:51 GMT 2013
     */
    private static class UpdateByExampleParms extends AcREmployeeGroupExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcREmployeeGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}