package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcRScheduleGroup;
import com.megaeyes.persistence.ibatis.model.AcRScheduleGroupExample;
import java.util.List;

public interface AcRScheduleGroupDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    void insert(AcRScheduleGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int updateByPrimaryKey(AcRScheduleGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int updateByPrimaryKeySelective(AcRScheduleGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    List selectByExample(AcRScheduleGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    AcRScheduleGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int deleteByExample(AcRScheduleGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int countByExample(AcRScheduleGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int updateByExampleSelective(AcRScheduleGroup record, AcRScheduleGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_R_SCHEDULE_GROUP
     *
     * @abatorgenerated Tue Jan 08 07:46:33 GMT 2013
     */
    int updateByExample(AcRScheduleGroup record, AcRScheduleGroupExample example);
}