package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcWorkAttendanceRule;
import com.megaeyes.persistence.ibatis.model.AcWorkAttendanceRuleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcWorkAttendanceRuleDAOImpl extends SqlMapClientDaoSupport implements AcWorkAttendanceRuleDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public AcWorkAttendanceRuleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public void insert(AcWorkAttendanceRule record) {
        getSqlMapClientTemplate().insert("AC_WORK_ATTENDANCE_RULE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int updateByPrimaryKey(AcWorkAttendanceRule record) {
        int rows = getSqlMapClientTemplate().update("AC_WORK_ATTENDANCE_RULE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int updateByPrimaryKeySelective(AcWorkAttendanceRule record) {
        int rows = getSqlMapClientTemplate().update("AC_WORK_ATTENDANCE_RULE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public List selectByExample(AcWorkAttendanceRuleExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_WORK_ATTENDANCE_RULE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public AcWorkAttendanceRule selectByPrimaryKey(String id) {
        AcWorkAttendanceRule key = new AcWorkAttendanceRule();
        key.setId(id);
        AcWorkAttendanceRule record = (AcWorkAttendanceRule) getSqlMapClientTemplate().queryForObject("AC_WORK_ATTENDANCE_RULE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int deleteByExample(AcWorkAttendanceRuleExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_WORK_ATTENDANCE_RULE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcWorkAttendanceRule key = new AcWorkAttendanceRule();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_WORK_ATTENDANCE_RULE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int countByExample(AcWorkAttendanceRuleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_WORK_ATTENDANCE_RULE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int updateByExampleSelective(AcWorkAttendanceRule record, AcWorkAttendanceRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_WORK_ATTENDANCE_RULE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    public int updateByExample(AcWorkAttendanceRule record, AcWorkAttendanceRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_WORK_ATTENDANCE_RULE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_WORK_ATTENDANCE_RULE
     *
     * @abatorgenerated Wed Feb 27 11:11:31 CST 2013
     */
    private static class UpdateByExampleParms extends AcWorkAttendanceRuleExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcWorkAttendanceRuleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}