package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcWorkRule;
import com.megaeyes.persistence.ibatis.model.AcWorkRuleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AcWorkRuleDAOImpl extends SqlMapClientDaoSupport implements AcWorkRuleDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public AcWorkRuleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public void insert(AcWorkRule record) {
        getSqlMapClientTemplate().insert("AC_WORK_RULE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int updateByPrimaryKey(AcWorkRule record) {
        int rows = getSqlMapClientTemplate().update("AC_WORK_RULE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int updateByPrimaryKeySelective(AcWorkRule record) {
        int rows = getSqlMapClientTemplate().update("AC_WORK_RULE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public List selectByExample(AcWorkRuleExample example) {
        List list = getSqlMapClientTemplate().queryForList("AC_WORK_RULE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public AcWorkRule selectByPrimaryKey(String id) {
        AcWorkRule key = new AcWorkRule();
        key.setId(id);
        AcWorkRule record = (AcWorkRule) getSqlMapClientTemplate().queryForObject("AC_WORK_RULE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int deleteByExample(AcWorkRuleExample example) {
        int rows = getSqlMapClientTemplate().delete("AC_WORK_RULE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        AcWorkRule key = new AcWorkRule();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("AC_WORK_RULE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int countByExample(AcWorkRuleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("AC_WORK_RULE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int updateByExampleSelective(AcWorkRule record, AcWorkRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_WORK_RULE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    public int updateByExample(AcWorkRule record, AcWorkRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("AC_WORK_RULE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    private static class UpdateByExampleParms extends AcWorkRuleExample {
        private Object record;

        public UpdateByExampleParms(Object record, AcWorkRuleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}