package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.AcWorkRule;
import com.megaeyes.persistence.ibatis.model.AcWorkRuleExample;
import java.util.List;

public interface AcWorkRuleDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    void insert(AcWorkRule record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int updateByPrimaryKey(AcWorkRule record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int updateByPrimaryKeySelective(AcWorkRule record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    List selectByExample(AcWorkRuleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    AcWorkRule selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int deleteByExample(AcWorkRuleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int countByExample(AcWorkRuleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int updateByExampleSelective(AcWorkRule record, AcWorkRuleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table AC_WORK_RULE
     *
     * @abatorgenerated Wed Feb 27 15:41:29 CST 2013
     */
    int updateByExample(AcWorkRule record, AcWorkRuleExample example);
}