package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.Branch;
import com.megaeyes.persistence.ibatis.model.BranchExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BranchDAOImpl extends SqlMapClientDaoSupport implements BranchDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public BranchDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public void insert(Branch record) {
        getSqlMapClientTemplate().insert("BRANCH.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int updateByPrimaryKey(Branch record) {
        int rows = getSqlMapClientTemplate().update("BRANCH.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int updateByPrimaryKeySelective(Branch record) {
        int rows = getSqlMapClientTemplate().update("BRANCH.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public List selectByExample(BranchExample example) {
        List list = getSqlMapClientTemplate().queryForList("BRANCH.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public Branch selectByPrimaryKey(String id) {
        Branch key = new Branch();
        key.setId(id);
        Branch record = (Branch) getSqlMapClientTemplate().queryForObject("BRANCH.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int deleteByExample(BranchExample example) {
        int rows = getSqlMapClientTemplate().delete("BRANCH.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int deleteByPrimaryKey(String id) {
        Branch key = new Branch();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("BRANCH.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int countByExample(BranchExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("BRANCH.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int updateByExampleSelective(Branch record, BranchExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("BRANCH.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    public int updateByExample(Branch record, BranchExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("BRANCH.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table BRANCH
     *
     * @abatorgenerated Tue Jan 08 06:32:24 GMT 2013
     */
    private static class UpdateByExampleParms extends BranchExample {
        private Object record;

        public UpdateByExampleParms(Object record, BranchExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}