package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpAssets;
import com.megaeyes.persistence.ibatis.model.EpAssetsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpAssetsDAOImpl extends SqlMapClientDaoSupport implements EpAssetsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public EpAssetsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public void insert(EpAssets record) {
        getSqlMapClientTemplate().insert("EP_ASSETS.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int updateByPrimaryKey(EpAssets record) {
        int rows = getSqlMapClientTemplate().update("EP_ASSETS.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int updateByPrimaryKeySelective(EpAssets record) {
        int rows = getSqlMapClientTemplate().update("EP_ASSETS.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public List selectByExample(EpAssetsExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_ASSETS.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public EpAssets selectByPrimaryKey(String id) {
        EpAssets key = new EpAssets();
        key.setId(id);
        EpAssets record = (EpAssets) getSqlMapClientTemplate().queryForObject("EP_ASSETS.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int deleteByExample(EpAssetsExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_ASSETS.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpAssets key = new EpAssets();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_ASSETS.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int countByExample(EpAssetsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_ASSETS.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int updateByExampleSelective(EpAssets record, EpAssetsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_ASSETS.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    public int updateByExample(EpAssets record, EpAssetsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_ASSETS.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_ASSETS
     *
     * @abatorgenerated Fri May 25 07:14:29 GMT 2012
     */
    private static class UpdateByExampleParms extends EpAssetsExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpAssetsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}