package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpClientGateway;
import com.megaeyes.persistence.ibatis.model.EpClientGatewayExample;
import java.util.List;

public interface EpClientGatewayDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	void insert(EpClientGateway record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int updateByPrimaryKey(EpClientGateway record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int updateByPrimaryKeySelective(EpClientGateway record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	List selectByExample(EpClientGatewayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	EpClientGateway selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int deleteByExample(EpClientGatewayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int countByExample(EpClientGatewayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int updateByExampleSelective(EpClientGateway record,
			EpClientGatewayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	int updateByExample(EpClientGateway record, EpClientGatewayExample example);
}