package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpClientGateway;
import com.megaeyes.persistence.ibatis.model.EpClientGatewayExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpClientGatewayDAOImpl extends SqlMapClientDaoSupport implements EpClientGatewayDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public EpClientGatewayDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public void insert(EpClientGateway record) {
		getSqlMapClientTemplate().insert(
				"EP_CLIENT_GATEWAY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int updateByPrimaryKey(EpClientGateway record) {
		int rows = getSqlMapClientTemplate().update(
				"EP_CLIENT_GATEWAY.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int updateByPrimaryKeySelective(EpClientGateway record) {
		int rows = getSqlMapClientTemplate()
				.update("EP_CLIENT_GATEWAY.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public List selectByExample(EpClientGatewayExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"EP_CLIENT_GATEWAY.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public EpClientGateway selectByPrimaryKey(String id) {
		EpClientGateway key = new EpClientGateway();
		key.setId(id);
		EpClientGateway record = (EpClientGateway) getSqlMapClientTemplate()
				.queryForObject(
						"EP_CLIENT_GATEWAY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int deleteByExample(EpClientGatewayExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"EP_CLIENT_GATEWAY.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int deleteByPrimaryKey(String id) {
		EpClientGateway key = new EpClientGateway();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"EP_CLIENT_GATEWAY.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int countByExample(EpClientGatewayExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"EP_CLIENT_GATEWAY.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int updateByExampleSelective(EpClientGateway record,
			EpClientGatewayExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("EP_CLIENT_GATEWAY.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	public int updateByExample(EpClientGateway record,
			EpClientGatewayExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("EP_CLIENT_GATEWAY.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table DL25.EP_CLIENT_GATEWAY
	 * @abatorgenerated  Sun Jan 06 15:36:10 CST 2013
	 */
	private static class UpdateByExampleParms extends EpClientGatewayExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				EpClientGatewayExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}