package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpControlServer;
import com.megaeyes.persistence.ibatis.model.EpControlServerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpControlServerDAOImpl extends SqlMapClientDaoSupport implements EpControlServerDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public EpControlServerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public void insert(EpControlServer record) {
        getSqlMapClientTemplate().insert("EP_CONTROL_SERVER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int updateByPrimaryKey(EpControlServer record) {
        int rows = getSqlMapClientTemplate().update("EP_CONTROL_SERVER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int updateByPrimaryKeySelective(EpControlServer record) {
        int rows = getSqlMapClientTemplate().update("EP_CONTROL_SERVER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public List selectByExample(EpControlServerExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_CONTROL_SERVER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public EpControlServer selectByPrimaryKey(String id) {
        EpControlServer key = new EpControlServer();
        key.setId(id);
        EpControlServer record = (EpControlServer) getSqlMapClientTemplate().queryForObject("EP_CONTROL_SERVER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int deleteByExample(EpControlServerExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_CONTROL_SERVER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpControlServer key = new EpControlServer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_CONTROL_SERVER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int countByExample(EpControlServerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_CONTROL_SERVER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int updateByExampleSelective(EpControlServer record, EpControlServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_CONTROL_SERVER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    public int updateByExample(EpControlServer record, EpControlServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_CONTROL_SERVER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_CONTROL_SERVER
     *
     * @abatorgenerated Wed May 09 14:04:45 CST 2012
     */
    private static class UpdateByExampleParms extends EpControlServerExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpControlServerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}