package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpDevice;
import com.megaeyes.persistence.ibatis.model.EpDeviceExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpDeviceDAOImpl extends SqlMapClientDaoSupport implements EpDeviceDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public EpDeviceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public void insert(EpDevice record) {
        getSqlMapClientTemplate().insert("EP_DEVICE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int updateByPrimaryKey(EpDevice record) {
        int rows = getSqlMapClientTemplate().update("EP_DEVICE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int updateByPrimaryKeySelective(EpDevice record) {
        int rows = getSqlMapClientTemplate().update("EP_DEVICE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public List selectByExample(EpDeviceExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_DEVICE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public EpDevice selectByPrimaryKey(String id) {
        EpDevice key = new EpDevice();
        key.setId(id);
        EpDevice record = (EpDevice) getSqlMapClientTemplate().queryForObject("EP_DEVICE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int deleteByExample(EpDeviceExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_DEVICE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpDevice key = new EpDevice();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_DEVICE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int countByExample(EpDeviceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_DEVICE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int updateByExampleSelective(EpDevice record, EpDeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_DEVICE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    public int updateByExample(EpDevice record, EpDeviceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_DEVICE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_DEVICE
     *
     * @abatorgenerated Thu Jun 07 02:51:01 GMT 2012
     */
    private static class UpdateByExampleParms extends EpDeviceExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpDeviceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}