package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpEventServer;
import com.megaeyes.persistence.ibatis.model.EpEventServerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpEventServerDAOImpl extends SqlMapClientDaoSupport implements EpEventServerDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public EpEventServerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public void insert(EpEventServer record) {
        getSqlMapClientTemplate().insert("EP_EVENT_SERVER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int updateByPrimaryKey(EpEventServer record) {
        int rows = getSqlMapClientTemplate().update("EP_EVENT_SERVER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int updateByPrimaryKeySelective(EpEventServer record) {
        int rows = getSqlMapClientTemplate().update("EP_EVENT_SERVER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public List selectByExample(EpEventServerExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_EVENT_SERVER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public EpEventServer selectByPrimaryKey(String id) {
        EpEventServer key = new EpEventServer();
        key.setId(id);
        EpEventServer record = (EpEventServer) getSqlMapClientTemplate().queryForObject("EP_EVENT_SERVER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int deleteByExample(EpEventServerExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_EVENT_SERVER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpEventServer key = new EpEventServer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_EVENT_SERVER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int countByExample(EpEventServerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_EVENT_SERVER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int updateByExampleSelective(EpEventServer record, EpEventServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_EVENT_SERVER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    public int updateByExample(EpEventServer record, EpEventServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_EVENT_SERVER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_EVENT_SERVER
     *
     * @abatorgenerated Tue Jun 12 10:42:28 CST 2012
     */
    private static class UpdateByExampleParms extends EpEventServerExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpEventServerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}