package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpOperation;
import com.megaeyes.persistence.ibatis.model.EpOperationExample;
import java.util.List;

public interface EpOperationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    void insert(EpOperation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int updateByPrimaryKey(EpOperation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int updateByPrimaryKeySelective(EpOperation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    List selectByExample(EpOperationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    EpOperation selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int deleteByExample(EpOperationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int countByExample(EpOperationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int updateByExampleSelective(EpOperation record, EpOperationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    int updateByExample(EpOperation record, EpOperationExample example);
}