package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpOperation;
import com.megaeyes.persistence.ibatis.model.EpOperationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpOperationDAOImpl extends SqlMapClientDaoSupport implements EpOperationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public EpOperationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public void insert(EpOperation record) {

        getSqlMapClientTemplate().insert("EP_OPERATION.abatorgenerated_insert", record);

    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int updateByPrimaryKey(EpOperation record) {

        int rows = getSqlMapClientTemplate().update("EP_OPERATION.abatorgenerated_updateByPrimaryKey", record);

        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int updateByPrimaryKeySelective(EpOperation record) {

        int rows = getSqlMapClientTemplate().update("EP_OPERATION.abatorgenerated_updateByPrimaryKeySelective", record);

        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public List selectByExample(EpOperationExample example) {

        List list = getSqlMapClientTemplate().queryForList("EP_OPERATION.abatorgenerated_selectByExample", example);

        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public EpOperation selectByPrimaryKey(String id) {
        EpOperation key = new EpOperation();
        key.setId(id);

        EpOperation record = (EpOperation) getSqlMapClientTemplate().queryForObject("EP_OPERATION.abatorgenerated_selectByPrimaryKey", key);

        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int deleteByExample(EpOperationExample example) {

        int rows = getSqlMapClientTemplate().delete("EP_OPERATION.abatorgenerated_deleteByExample", example);

        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpOperation key = new EpOperation();
        key.setId(id);

        int rows = getSqlMapClientTemplate().delete("EP_OPERATION.abatorgenerated_deleteByPrimaryKey", key);

        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int countByExample(EpOperationExample example) {

        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_OPERATION.abatorgenerated_countByExample", example);

        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int updateByExampleSelective(EpOperation record, EpOperationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);

        int rows = getSqlMapClientTemplate().update("EP_OPERATION.abatorgenerated_updateByExampleSelective", parms);

        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    public int updateByExample(EpOperation record, EpOperationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);

        int rows = getSqlMapClientTemplate().update("EP_OPERATION.abatorgenerated_updateByExample", parms);

        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_OPERATION
     *
     * @abatorgenerated Tue May 22 09:23:38 GMT 2012
     */
    private static class UpdateByExampleParms extends EpOperationExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpOperationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}