package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpProber;
import com.megaeyes.persistence.ibatis.model.EpProberExample;
import java.util.List;

public interface EpProberDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    void insert(EpProber record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    int updateByPrimaryKey(EpProber record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    int updateByPrimaryKeySelective(EpProber record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    List selectByExample(EpProberExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    EpProber selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    int deleteByExample(EpProberExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    int deleteByPrimaryKey(String id);
}