package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpProber;
import com.megaeyes.persistence.ibatis.model.EpProberExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProberDAOImpl extends SqlMapClientDaoSupport implements EpProberDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public EpProberDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public void insert(EpProber record) {
        getSqlMapClientTemplate().insert("EP_PROBER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public int updateByPrimaryKey(EpProber record) {
        int rows = getSqlMapClientTemplate().update("EP_PROBER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public int updateByPrimaryKeySelective(EpProber record) {
        int rows = getSqlMapClientTemplate().update("EP_PROBER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public List selectByExample(EpProberExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_PROBER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public EpProber selectByPrimaryKey(String id) {
        EpProber key = new EpProber();
        key.setId(id);
        EpProber record = (EpProber) getSqlMapClientTemplate().queryForObject("EP_PROBER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public int deleteByExample(EpProberExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_PROBER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_PROBER
     *
     * @abatorgenerated Mon May 07 15:44:50 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpProber key = new EpProber();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_PROBER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}