package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpProberType;
import com.megaeyes.persistence.ibatis.model.EpProberTypeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProberTypeDAOImpl extends SqlMapClientDaoSupport implements EpProberTypeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public EpProberTypeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public void insert(EpProberType record) {
        getSqlMapClientTemplate().insert("EP_PROBER_TYPE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int updateByPrimaryKey(EpProberType record) {
        int rows = getSqlMapClientTemplate().update("EP_PROBER_TYPE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int updateByPrimaryKeySelective(EpProberType record) {
        int rows = getSqlMapClientTemplate().update("EP_PROBER_TYPE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public List selectByExample(EpProberTypeExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_PROBER_TYPE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public EpProberType selectByPrimaryKey(String id) {
        EpProberType key = new EpProberType();
        key.setId(id);
        EpProberType record = (EpProberType) getSqlMapClientTemplate().queryForObject("EP_PROBER_TYPE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int deleteByExample(EpProberTypeExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_PROBER_TYPE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpProberType key = new EpProberType();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_PROBER_TYPE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int countByExample(EpProberTypeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_PROBER_TYPE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int updateByExampleSelective(EpProberType record, EpProberTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROBER_TYPE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    public int updateByExample(EpProberType record, EpProberTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROBER_TYPE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_PROBER_TYPE
     *
     * @abatorgenerated Thu May 10 15:05:07 CST 2012
     */
    private static class UpdateByExampleParms extends EpProberTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpProberTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}