package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpRDoorVic;
import com.megaeyes.persistence.ibatis.model.EpRDoorVicExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpRDoorVicDAOImpl extends SqlMapClientDaoSupport implements EpRDoorVicDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public EpRDoorVicDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public void insert(EpRDoorVic record) {
        getSqlMapClientTemplate().insert("EP_R_DOOR_VIC.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int updateByPrimaryKey(EpRDoorVic record) {
        int rows = getSqlMapClientTemplate().update("EP_R_DOOR_VIC.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int updateByPrimaryKeySelective(EpRDoorVic record) {
        int rows = getSqlMapClientTemplate().update("EP_R_DOOR_VIC.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public List selectByExample(EpRDoorVicExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_R_DOOR_VIC.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public EpRDoorVic selectByPrimaryKey(String id) {
        EpRDoorVic key = new EpRDoorVic();
        key.setId(id);
        EpRDoorVic record = (EpRDoorVic) getSqlMapClientTemplate().queryForObject("EP_R_DOOR_VIC.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int deleteByExample(EpRDoorVicExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_R_DOOR_VIC.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpRDoorVic key = new EpRDoorVic();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_R_DOOR_VIC.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int countByExample(EpRDoorVicExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_R_DOOR_VIC.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int updateByExampleSelective(EpRDoorVic record, EpRDoorVicExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_R_DOOR_VIC.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    public int updateByExample(EpRDoorVic record, EpRDoorVicExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_R_DOOR_VIC.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_R_DOOR_VIC
     *
     * @abatorgenerated Wed May 23 07:27:41 GMT 2012
     */
    private static class UpdateByExampleParms extends EpRDoorVicExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpRDoorVicExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}