package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpRTaskEmployee;
import com.megaeyes.persistence.ibatis.model.EpRTaskEmployeeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpRTaskEmployeeDAOImpl extends SqlMapClientDaoSupport implements EpRTaskEmployeeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public EpRTaskEmployeeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public void insert(EpRTaskEmployee record) {
        getSqlMapClientTemplate().insert("EP_R_TASK_EMPLOYEE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int updateByPrimaryKey(EpRTaskEmployee record) {
        int rows = getSqlMapClientTemplate().update("EP_R_TASK_EMPLOYEE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int updateByPrimaryKeySelective(EpRTaskEmployee record) {
        int rows = getSqlMapClientTemplate().update("EP_R_TASK_EMPLOYEE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public List selectByExample(EpRTaskEmployeeExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_R_TASK_EMPLOYEE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public EpRTaskEmployee selectByPrimaryKey(String id) {
        EpRTaskEmployee key = new EpRTaskEmployee();
        key.setId(id);
        EpRTaskEmployee record = (EpRTaskEmployee) getSqlMapClientTemplate().queryForObject("EP_R_TASK_EMPLOYEE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int deleteByExample(EpRTaskEmployeeExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_R_TASK_EMPLOYEE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpRTaskEmployee key = new EpRTaskEmployee();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_R_TASK_EMPLOYEE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int countByExample(EpRTaskEmployeeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_R_TASK_EMPLOYEE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int updateByExampleSelective(EpRTaskEmployee record, EpRTaskEmployeeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_R_TASK_EMPLOYEE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    public int updateByExample(EpRTaskEmployee record, EpRTaskEmployeeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_R_TASK_EMPLOYEE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_R_TASK_EMPLOYEE
     *
     * @abatorgenerated Mon May 14 09:29:45 CST 2012
     */
    private static class UpdateByExampleParms extends EpRTaskEmployeeExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpRTaskEmployeeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}