package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpRTrackPreset;
import com.megaeyes.persistence.ibatis.model.EpRTrackPresetExample;
import java.util.List;

public interface EpRTrackPresetDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    void insert(EpRTrackPreset record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    List selectByExample(EpRTrackPresetExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    int deleteByExample(EpRTrackPresetExample example);
}