package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpRTrackPreset;
import com.megaeyes.persistence.ibatis.model.EpRTrackPresetExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpRTrackPresetDAOImpl extends SqlMapClientDaoSupport implements EpRTrackPresetDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    public EpRTrackPresetDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    public void insert(EpRTrackPreset record) {
        getSqlMapClientTemplate().insert("EP_R_TRACK_PRESET.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    public List selectByExample(EpRTrackPresetExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_R_TRACK_PRESET.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_R_TRACK_PRESET
     *
     * @abatorgenerated Wed Apr 18 14:52:13 CST 2012
     */
    public int deleteByExample(EpRTrackPresetExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_R_TRACK_PRESET.abatorgenerated_deleteByExample", example);
        return rows;
    }
}