package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpScheme;
import com.megaeyes.persistence.ibatis.model.EpSchemeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpSchemeDAOImpl extends SqlMapClientDaoSupport implements EpSchemeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public EpSchemeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public void insert(EpScheme record) {
        getSqlMapClientTemplate().insert("EP_SCHEME.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int updateByPrimaryKey(EpScheme record) {
        int rows = getSqlMapClientTemplate().update("EP_SCHEME.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int updateByPrimaryKeySelective(EpScheme record) {
        int rows = getSqlMapClientTemplate().update("EP_SCHEME.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public List selectByExample(EpSchemeExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_SCHEME.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public EpScheme selectByPrimaryKey(String id) {
        EpScheme key = new EpScheme();
        key.setId(id);
        EpScheme record = (EpScheme) getSqlMapClientTemplate().queryForObject("EP_SCHEME.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int deleteByExample(EpSchemeExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_SCHEME.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpScheme key = new EpScheme();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_SCHEME.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int countByExample(EpSchemeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_SCHEME.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int updateByExampleSelective(EpScheme record, EpSchemeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_SCHEME.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    public int updateByExample(EpScheme record, EpSchemeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_SCHEME.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_SCHEME
     *
     * @abatorgenerated Thu Jun 14 08:50:12 GMT 2012
     */
    private static class UpdateByExampleParms extends EpSchemeExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpSchemeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}