package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpTaskStepHistory;
import com.megaeyes.persistence.ibatis.model.EpTaskStepHistoryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpTaskStepHistoryDAOImpl extends SqlMapClientDaoSupport implements EpTaskStepHistoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public EpTaskStepHistoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public void insert(EpTaskStepHistory record) {
        getSqlMapClientTemplate().insert("EP_TASK_STEP_HISTORY.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int updateByPrimaryKey(EpTaskStepHistory record) {
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP_HISTORY.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int updateByPrimaryKeySelective(EpTaskStepHistory record) {
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP_HISTORY.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public List selectByExample(EpTaskStepHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_TASK_STEP_HISTORY.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public EpTaskStepHistory selectByPrimaryKey(String id) {
        EpTaskStepHistory key = new EpTaskStepHistory();
        key.setId(id);
        EpTaskStepHistory record = (EpTaskStepHistory) getSqlMapClientTemplate().queryForObject("EP_TASK_STEP_HISTORY.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int deleteByExample(EpTaskStepHistoryExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_TASK_STEP_HISTORY.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpTaskStepHistory key = new EpTaskStepHistory();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_TASK_STEP_HISTORY.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int countByExample(EpTaskStepHistoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_TASK_STEP_HISTORY.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int updateByExampleSelective(EpTaskStepHistory record, EpTaskStepHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP_HISTORY.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    public int updateByExample(EpTaskStepHistory record, EpTaskStepHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP_HISTORY.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_TASK_STEP_HISTORY
     *
     * @abatorgenerated Thu May 17 14:22:32 CST 2012
     */
    private static class UpdateByExampleParms extends EpTaskStepHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpTaskStepHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}