package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpTaskStep;
import com.megaeyes.persistence.ibatis.model.EpTaskStepExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpTaskStepDAOImpl extends SqlMapClientDaoSupport implements EpTaskStepDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public EpTaskStepDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public void insert(EpTaskStep record) {
        getSqlMapClientTemplate().insert("EP_TASK_STEP.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int updateByPrimaryKey(EpTaskStep record) {
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int updateByPrimaryKeySelective(EpTaskStep record) {
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public List selectByExample(EpTaskStepExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_TASK_STEP.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public EpTaskStep selectByPrimaryKey(String id) {
        EpTaskStep key = new EpTaskStep();
        key.setId(id);
        EpTaskStep record = (EpTaskStep) getSqlMapClientTemplate().queryForObject("EP_TASK_STEP.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int deleteByExample(EpTaskStepExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_TASK_STEP.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpTaskStep key = new EpTaskStep();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_TASK_STEP.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int countByExample(EpTaskStepExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_TASK_STEP.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int updateByExampleSelective(EpTaskStep record, EpTaskStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    public int updateByExample(EpTaskStep record, EpTaskStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_TASK_STEP.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_TASK_STEP
     *
     * @abatorgenerated Fri May 11 15:43:23 CST 2012
     */
    private static class UpdateByExampleParms extends EpTaskStepExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpTaskStepExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}