package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpTask;
import com.megaeyes.persistence.ibatis.model.EpTaskExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpTaskDAOImpl extends SqlMapClientDaoSupport implements EpTaskDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public EpTaskDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public void insert(EpTask record) {
        getSqlMapClientTemplate().insert("EP_TASK.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int updateByPrimaryKey(EpTask record) {
        int rows = getSqlMapClientTemplate().update("EP_TASK.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int updateByPrimaryKeySelective(EpTask record) {
        int rows = getSqlMapClientTemplate().update("EP_TASK.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public List selectByExample(EpTaskExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_TASK.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public EpTask selectByPrimaryKey(String id) {
        EpTask key = new EpTask();
        key.setId(id);
        EpTask record = (EpTask) getSqlMapClientTemplate().queryForObject("EP_TASK.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int deleteByExample(EpTaskExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_TASK.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpTask key = new EpTask();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_TASK.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int countByExample(EpTaskExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_TASK.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int updateByExampleSelective(EpTask record, EpTaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_TASK.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    public int updateByExample(EpTask record, EpTaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_TASK.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    private static class UpdateByExampleParms extends EpTaskExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpTaskExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}