package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpTask;
import com.megaeyes.persistence.ibatis.model.EpTaskExample;
import java.util.List;

public interface EpTaskDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    void insert(EpTask record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int updateByPrimaryKey(EpTask record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int updateByPrimaryKeySelective(EpTask record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    List selectByExample(EpTaskExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    EpTask selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int deleteByExample(EpTaskExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int countByExample(EpTaskExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int updateByExampleSelective(EpTask record, EpTaskExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK
     *
     * @abatorgenerated Fri May 11 15:42:53 CST 2012
     */
    int updateByExample(EpTask record, EpTaskExample example);
}