package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpTaskHistory;
import com.megaeyes.persistence.ibatis.model.EpTaskHistoryExample;
import java.util.List;

public interface EpTaskHistoryDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    void insert(EpTaskHistory record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int updateByPrimaryKey(EpTaskHistory record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int updateByPrimaryKeySelective(EpTaskHistory record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    List selectByExample(EpTaskHistoryExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    EpTaskHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int deleteByExample(EpTaskHistoryExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int countByExample(EpTaskHistoryExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int updateByExampleSelective(EpTaskHistory record, EpTaskHistoryExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.EP_TASK_HISTORY
     *
     * @abatorgenerated Wed May 23 10:12:04 CST 2012
     */
    int updateByExample(EpTaskHistory record, EpTaskHistoryExample example);
}