package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.EpTrack;
import com.megaeyes.persistence.ibatis.model.EpTrackExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpTrackDAOImpl extends SqlMapClientDaoSupport implements EpTrackDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public EpTrackDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public void insert(EpTrack record) {
        getSqlMapClientTemplate().insert("EP_TRACK.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public int updateByPrimaryKey(EpTrack record) {
        int rows = getSqlMapClientTemplate().update("EP_TRACK.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public int updateByPrimaryKeySelective(EpTrack record) {
        int rows = getSqlMapClientTemplate().update("EP_TRACK.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public List selectByExample(EpTrackExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_TRACK.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public EpTrack selectByPrimaryKey(String id) {
        EpTrack key = new EpTrack();
        key.setId(id);
        EpTrack record = (EpTrack) getSqlMapClientTemplate().queryForObject("EP_TRACK.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public int deleteByExample(EpTrackExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_TRACK.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EP_TRACK
     *
     * @abatorgenerated Wed Apr 18 14:51:35 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        EpTrack key = new EpTrack();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("EP_TRACK.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}