package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.IvuTask;
import com.megaeyes.persistence.ibatis.model.IvuTaskExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IvuTaskDAOImpl extends SqlMapClientDaoSupport implements IvuTaskDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public IvuTaskDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public void insert(IvuTask record) {
        getSqlMapClientTemplate().insert("IVU_TASK.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int updateByPrimaryKey(IvuTask record) {
        int rows = getSqlMapClientTemplate().update("IVU_TASK.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int updateByPrimaryKeySelective(IvuTask record) {
        int rows = getSqlMapClientTemplate().update("IVU_TASK.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public List selectByExample(IvuTaskExample example) {
        List list = getSqlMapClientTemplate().queryForList("IVU_TASK.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public IvuTask selectByPrimaryKey(String id) {
        IvuTask key = new IvuTask();
        key.setId(id);
        IvuTask record = (IvuTask) getSqlMapClientTemplate().queryForObject("IVU_TASK.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int deleteByExample(IvuTaskExample example) {
        int rows = getSqlMapClientTemplate().delete("IVU_TASK.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int deleteByPrimaryKey(String id) {
        IvuTask key = new IvuTask();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("IVU_TASK.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int countByExample(IvuTaskExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IVU_TASK.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int updateByExampleSelective(IvuTask record, IvuTaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IVU_TASK.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    public int updateByExample(IvuTask record, IvuTaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IVU_TASK.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table IVU_TASK
     *
     * @abatorgenerated Tue Jul 03 06:17:17 GMT 2012
     */
    private static class UpdateByExampleParms extends IvuTaskExample {
        private Object record;

        public UpdateByExampleParms(Object record, IvuTaskExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}