package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.MediaGatewayServer;
import com.megaeyes.persistence.ibatis.model.MediaGatewayServerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MediaGatewayServerDAOImpl extends SqlMapClientDaoSupport implements MediaGatewayServerDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public MediaGatewayServerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public void insert(MediaGatewayServer record) {
        getSqlMapClientTemplate().insert("MEDIA_GATEWAY_SERVER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int updateByPrimaryKey(MediaGatewayServer record) {
        int rows = getSqlMapClientTemplate().update("MEDIA_GATEWAY_SERVER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int updateByPrimaryKeySelective(MediaGatewayServer record) {
        int rows = getSqlMapClientTemplate().update("MEDIA_GATEWAY_SERVER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public List selectByExample(MediaGatewayServerExample example) {
        List list = getSqlMapClientTemplate().queryForList("MEDIA_GATEWAY_SERVER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public MediaGatewayServer selectByPrimaryKey(String id) {
        MediaGatewayServer key = new MediaGatewayServer();
        key.setId(id);
        MediaGatewayServer record = (MediaGatewayServer) getSqlMapClientTemplate().queryForObject("MEDIA_GATEWAY_SERVER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int deleteByExample(MediaGatewayServerExample example) {
        int rows = getSqlMapClientTemplate().delete("MEDIA_GATEWAY_SERVER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        MediaGatewayServer key = new MediaGatewayServer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("MEDIA_GATEWAY_SERVER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int countByExample(MediaGatewayServerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MEDIA_GATEWAY_SERVER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int updateByExampleSelective(MediaGatewayServer record, MediaGatewayServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MEDIA_GATEWAY_SERVER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    public int updateByExample(MediaGatewayServer record, MediaGatewayServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MEDIA_GATEWAY_SERVER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table HBDW1.MEDIA_GATEWAY_SERVER
     *
     * @abatorgenerated Wed May 16 16:06:10 CST 2012
     */
    private static class UpdateByExampleParms extends MediaGatewayServerExample {
        private Object record;

        public UpdateByExampleParms(Object record, MediaGatewayServerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}