package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.PlatformSubscribe;
import com.megaeyes.persistence.ibatis.model.PlatformSubscribeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PlatformSubscribeDAOImpl extends SqlMapClientDaoSupport implements PlatformSubscribeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public PlatformSubscribeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public void insert(PlatformSubscribe record) {
        getSqlMapClientTemplate().insert("PLATFORM_SUBSCRIBE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public int updateByPrimaryKey(PlatformSubscribe record) {
        int rows = getSqlMapClientTemplate().update("PLATFORM_SUBSCRIBE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public int updateByPrimaryKeySelective(PlatformSubscribe record) {
        int rows = getSqlMapClientTemplate().update("PLATFORM_SUBSCRIBE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public List selectByExample(PlatformSubscribeExample example) {
        List list = getSqlMapClientTemplate().queryForList("PLATFORM_SUBSCRIBE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public PlatformSubscribe selectByPrimaryKey(String id) {
        PlatformSubscribe key = new PlatformSubscribe();
        key.setId(id);
        PlatformSubscribe record = (PlatformSubscribe) getSqlMapClientTemplate().queryForObject("PLATFORM_SUBSCRIBE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public int deleteByExample(PlatformSubscribeExample example) {
        int rows = getSqlMapClientTemplate().delete("PLATFORM_SUBSCRIBE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PLATFORM_SUBSCRIBE
     *
     * @abatorgenerated Thu May 03 09:55:50 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        PlatformSubscribe key = new PlatformSubscribe();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("PLATFORM_SUBSCRIBE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}