package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.RUserAccontrol;
import com.megaeyes.persistence.ibatis.model.RUserAccontrolExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RUserAccontrolDAOImpl extends SqlMapClientDaoSupport implements RUserAccontrolDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table R_USER_ACCONTROL
     *
     * @abatorgenerated Mon Apr 16 10:08:17 CST 2012
     */
    public RUserAccontrolDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table R_USER_ACCONTROL
     *
     * @abatorgenerated Mon Apr 16 10:08:17 CST 2012
     */
    public void insert(RUserAccontrol record) {
        getSqlMapClientTemplate().insert("R_USER_ACCONTROL.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table R_USER_ACCONTROL
     *
     * @abatorgenerated Mon Apr 16 10:08:17 CST 2012
     */
    public List selectByExample(RUserAccontrolExample example) {
        List list = getSqlMapClientTemplate().queryForList("R_USER_ACCONTROL.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table R_USER_ACCONTROL
     *
     * @abatorgenerated Mon Apr 16 10:08:17 CST 2012
     */
    public int deleteByExample(RUserAccontrolExample example) {
        int rows = getSqlMapClientTemplate().delete("R_USER_ACCONTROL.abatorgenerated_deleteByExample", example);
        return rows;
    }
}