package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.SipServer;
import com.megaeyes.persistence.ibatis.model.SipServerExample;
import java.util.List;

public interface SipServerDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    void insert(SipServer record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int updateByPrimaryKey(SipServer record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int updateByPrimaryKeySelective(SipServer record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    List selectByExample(SipServerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    SipServer selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int deleteByExample(SipServerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int countByExample(SipServerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int updateByExampleSelective(SipServer record, SipServerExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    int updateByExample(SipServer record, SipServerExample example);
}