package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.SipServer;
import com.megaeyes.persistence.ibatis.model.SipServerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SipServerDAOImpl extends SqlMapClientDaoSupport implements SipServerDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public SipServerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public void insert(SipServer record) {
        getSqlMapClientTemplate().insert("SIP_SERVER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int updateByPrimaryKey(SipServer record) {
        int rows = getSqlMapClientTemplate().update("SIP_SERVER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int updateByPrimaryKeySelective(SipServer record) {
        int rows = getSqlMapClientTemplate().update("SIP_SERVER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public List selectByExample(SipServerExample example) {
        List list = getSqlMapClientTemplate().queryForList("SIP_SERVER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public SipServer selectByPrimaryKey(String id) {
        SipServer key = new SipServer();
        key.setId(id);
        SipServer record = (SipServer) getSqlMapClientTemplate().queryForObject("SIP_SERVER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int deleteByExample(SipServerExample example) {
        int rows = getSqlMapClientTemplate().delete("SIP_SERVER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        SipServer key = new SipServer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("SIP_SERVER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int countByExample(SipServerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SIP_SERVER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int updateByExampleSelective(SipServer record, SipServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SIP_SERVER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    public int updateByExample(SipServer record, SipServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SIP_SERVER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table MEGA.SIP_SERVER
     *
     * @abatorgenerated Tue Jun 12 14:32:41 CST 2012
     */
    private static class UpdateByExampleParms extends SipServerExample {
        private Object record;

        public UpdateByExampleParms(Object record, SipServerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}