package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.TempResources;
import com.megaeyes.persistence.ibatis.model.TempResourcesExample;
import java.util.List;

public interface TempResourcesDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    void insert(TempResources record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    int updateByPrimaryKey(TempResources record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    int updateByPrimaryKeySelective(TempResources record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    List selectByExample(TempResourcesExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    TempResources selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    int deleteByExample(TempResourcesExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    int deleteByPrimaryKey(String id);
}