package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.TempResources;
import com.megaeyes.persistence.ibatis.model.TempResourcesExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TempResourcesDAOImpl extends SqlMapClientDaoSupport implements TempResourcesDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public TempResourcesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public void insert(TempResources record) {
        getSqlMapClientTemplate().insert("TEMP_RESOURCES.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public int updateByPrimaryKey(TempResources record) {
        int rows = getSqlMapClientTemplate().update("TEMP_RESOURCES.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public int updateByPrimaryKeySelective(TempResources record) {
        int rows = getSqlMapClientTemplate().update("TEMP_RESOURCES.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public List selectByExample(TempResourcesExample example) {
        List list = getSqlMapClientTemplate().queryForList("TEMP_RESOURCES.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public TempResources selectByPrimaryKey(String id) {
        TempResources key = new TempResources();
        key.setId(id);
        TempResources record = (TempResources) getSqlMapClientTemplate().queryForObject("TEMP_RESOURCES.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public int deleteByExample(TempResourcesExample example) {
        int rows = getSqlMapClientTemplate().delete("TEMP_RESOURCES.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TEMP_RESOURCES
     *
     * @abatorgenerated Fri Apr 20 15:21:19 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        TempResources key = new TempResources();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TEMP_RESOURCES.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}