package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.ThirdPartyPlatform;
import com.megaeyes.persistence.ibatis.model.ThirdPartyPlatformExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ThirdPartyPlatformDAOImpl extends SqlMapClientDaoSupport implements ThirdPartyPlatformDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public ThirdPartyPlatformDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public void insert(ThirdPartyPlatform record) {
        getSqlMapClientTemplate().insert("THIRD_PARTY_PLATFORM.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public int updateByPrimaryKey(ThirdPartyPlatform record) {
        int rows = getSqlMapClientTemplate().update("THIRD_PARTY_PLATFORM.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public int updateByPrimaryKeySelective(ThirdPartyPlatform record) {
        int rows = getSqlMapClientTemplate().update("THIRD_PARTY_PLATFORM.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public List selectByExample(ThirdPartyPlatformExample example) {
        List list = getSqlMapClientTemplate().queryForList("THIRD_PARTY_PLATFORM.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public ThirdPartyPlatform selectByPrimaryKey(String id) {
        ThirdPartyPlatform key = new ThirdPartyPlatform();
        key.setId(id);
        ThirdPartyPlatform record = (ThirdPartyPlatform) getSqlMapClientTemplate().queryForObject("THIRD_PARTY_PLATFORM.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public int deleteByExample(ThirdPartyPlatformExample example) {
        int rows = getSqlMapClientTemplate().delete("THIRD_PARTY_PLATFORM.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table THIRD_PARTY_PLATFORM
     *
     * @abatorgenerated Wed May 02 13:22:23 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        ThirdPartyPlatform key = new ThirdPartyPlatform();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("THIRD_PARTY_PLATFORM.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}