package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.UserSubscribe;
import com.megaeyes.persistence.ibatis.model.UserSubscribeExample;
import java.util.List;

public interface UserSubscribeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    void insert(UserSubscribe record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    int updateByPrimaryKey(UserSubscribe record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    int updateByPrimaryKeySelective(UserSubscribe record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    List selectByExample(UserSubscribeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    UserSubscribe selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    int deleteByExample(UserSubscribeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    int deleteByPrimaryKey(String id);
}