package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.UserSubscribe;
import com.megaeyes.persistence.ibatis.model.UserSubscribeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserSubscribeDAOImpl extends SqlMapClientDaoSupport implements UserSubscribeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public UserSubscribeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public void insert(UserSubscribe record) {
        getSqlMapClientTemplate().insert("USER_SUBSCRIBE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public int updateByPrimaryKey(UserSubscribe record) {
        int rows = getSqlMapClientTemplate().update("USER_SUBSCRIBE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public int updateByPrimaryKeySelective(UserSubscribe record) {
        int rows = getSqlMapClientTemplate().update("USER_SUBSCRIBE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public List selectByExample(UserSubscribeExample example) {
        List list = getSqlMapClientTemplate().queryForList("USER_SUBSCRIBE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public UserSubscribe selectByPrimaryKey(String id) {
        UserSubscribe key = new UserSubscribe();
        key.setId(id);
        UserSubscribe record = (UserSubscribe) getSqlMapClientTemplate().queryForObject("USER_SUBSCRIBE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public int deleteByExample(UserSubscribeExample example) {
        int rows = getSqlMapClientTemplate().delete("USER_SUBSCRIBE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table USER_SUBSCRIBE
     *
     * @abatorgenerated Fri Apr 20 15:16:15 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        UserSubscribe key = new UserSubscribe();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("USER_SUBSCRIBE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}