package com.megaeyes.persistence.ibatis.iface;

import com.megaeyes.persistence.ibatis.model.VideoInputServer;
import com.megaeyes.persistence.ibatis.model.VideoInputServerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VideoInputServerDAOImpl extends SqlMapClientDaoSupport implements VideoInputServerDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public VideoInputServerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public void insert(VideoInputServer record) {
        getSqlMapClientTemplate().insert("VIDEO_INPUT_SERVER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int updateByPrimaryKey(VideoInputServer record) {
        int rows = getSqlMapClientTemplate().update("VIDEO_INPUT_SERVER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int updateByPrimaryKeySelective(VideoInputServer record) {
        int rows = getSqlMapClientTemplate().update("VIDEO_INPUT_SERVER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public List selectByExample(VideoInputServerExample example) {
        List list = getSqlMapClientTemplate().queryForList("VIDEO_INPUT_SERVER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public VideoInputServer selectByPrimaryKey(String id) {
        VideoInputServer key = new VideoInputServer();
        key.setId(id);
        VideoInputServer record = (VideoInputServer) getSqlMapClientTemplate().queryForObject("VIDEO_INPUT_SERVER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int deleteByExample(VideoInputServerExample example) {
        int rows = getSqlMapClientTemplate().delete("VIDEO_INPUT_SERVER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int deleteByPrimaryKey(String id) {
        VideoInputServer key = new VideoInputServer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("VIDEO_INPUT_SERVER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int countByExample(VideoInputServerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("VIDEO_INPUT_SERVER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int updateByExampleSelective(VideoInputServer record, VideoInputServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("VIDEO_INPUT_SERVER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    public int updateByExample(VideoInputServer record, VideoInputServerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("VIDEO_INPUT_SERVER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table JHDYJDBMEGAJQ33.VIDEO_INPUT_SERVER
     *
     * @abatorgenerated Thu May 10 14:26:01 CST 2012
     */
    private static class UpdateByExampleParms extends VideoInputServerExample {
        private Object record;

        public UpdateByExampleParms(Object record, VideoInputServerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}